### ISSUE TITLE
Empty host ingress bug

### ISSUE THREAD

**Issue by andrewm41** [haproxytech/kubernetes-ingress#103]
When I define Ingress with empty host, no servers are created in backend section in /etc/haproxy/haproxy.cfg

have to create Ingress with random host name and then redefine it with empty value, that fixes the bug, but it is rather ugly solution.

Ingress example:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  namespace: default
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        backend:
          serviceName: my-service
          servicePort: 80
```
