### ISSUE TITLE
Service port change not reflected

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#12]
hi,

When I change a service port, then the ingress controller does not follow up and HAProxy is still configured with the old port.

Given the following Ingress rule:
```
kind: Ingress
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: service1
          servicePort: http
```
And Service definition:
```
kind: Service
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
```
All of this works.

Now, I update my service to match the following:
And Service definition:
```
kind: Service
spec:
  ports:
    - port: 10000
      targetPort: http
      protocol: TCP
      name: http
```
Then my HAProxy configuration is not updated and port in this backend is still set to the old value (8080)

**Comment by jhohertz** [comment]
Confirming I saw this as well in evaluating while trying to figure out what was going on in #14

**Comment by oktalz** [comment]
named `targetPort` is not supported yet.

However if that was supported it still wouldn't work.
Since you defined targetPort, port is not relevant for controller.
Service port is only interesting if targetPort is not defined.

Controller wants to send traffic not to service, but to pods directly to avoid extra hop.

**Comment by Meroje** [comment]
> Since you defined targetPort, port is not relevant for controller.

This issue would still be valid if the ingress did use the targetPort, it is not applying the change.

> Controller wants to send traffic not to service, but to pods directly to avoid extra hop.

I would in fact expect it to read the endpoints to know the pods, this would skip all issues about inferring what a service means

```
kubectl get endpoints service1 -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  name: service1
  namespace: default
subsets:
- addresses:
  - ip: 100.96.69.31
    [...]
  ports:
  - name: http
    port: 8080
    protocol: TCP
```

**Comment by oktalz** [comment]
Hi,
from version 1.1.2 controller is using Endpoints api from k8s, 
and named ports are also supported.

**Comment by ernoaapa** [comment]
I believe that (probably) this bug still exists.  Here's example how to reproduce
Before:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-service
  namespace: example-service
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: example-service
          servicePort: 8080
```

Change the `servicePort` to something else:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-service
  namespace: example-service
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: example-service
          servicePort: 80
```

In the haproxy-ignress logs:
```shell
2019/07/29 09:38:29 controller.go:274 11: backend example-service-hello-kubernetes-80 does not exist
2019/07/29 09:38:29 controller-haproxy.go:150: 14: ERR transactionId=498b5e84-e4b6-42bf-8c4f-a7e547842599
msg="Proxy 'http': unable to find required use_backend: 'example-service-hello-kubernetes-80'."
```
The backend name changes because the port number changes, which cause the backend change and it fails to update (remove old & create new) the backend.
Bad thing is that the only way to fix this was deleting the Pod. When a fresh pod comes up, all works nicely!
