### ISSUE TITLE
HAProxy Controller is not redirecting from HTTP to HTTPS

### ISSUE THREAD

**Issue by git4suvendu** [haproxytech/kubernetes-ingress#122]
I am running an application, HAProxy Controller and Ingress resource in GKE. I have a domain (mydomain.co.uk) where "A" record is pointing to the L7 load-balancer. The domain has provided an SSL certificate, key which I have used as a secret in the GKE cluster and in Ingress resource. In the Ingress YAML I have provided annotations to always redirect from HTTP to HTTPS. But it's not working. 

Is it a bug or I am doing something wrong?

Just to mention, I haven't set up any cert-manager, cluster issue etc. for the certificate as I don't think it's required because already I have got the certificate from the domain provider and I am able to connect the application using HTTPS. Only the redirection is not working.

Note# I have masked the domain name. 

**Ingress YAML**
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fanout-ingress-haproxy
  namespace: xyz-product
  labels:                     # Labels that will be applied to this resource
    app: prod-user-reg-app
  annotations:
    kubernetes.io/ingress.global-static-ip-name: prod-reg-static-ip  #Defined in GCP platform. A Static IP needs to be created in the GCP.
    ingress.kubernetes.io/force-ssl-redirect: "true"
    haproxy.org/ingress.class: "haproxy"
    haproxy.org/load-balance: "leastconn"  #roundrobin
    haproxy.org/forwarded-for: "enabled"
    haproxy.org/ssl-certificate: "xyz-product/prod-tls-secret"
    haproxy.org/ssl-redirect: "ON"
    haproxy.org/ssl-redirect-code: "303"
spec:
  tls:
  - hosts:
    - mydomain.co.uk
    secretName: prod-tls-secret
  rules:
  - host: apps.mydomain.co.uk
    http:
      paths:
      - path: /user-reg/create/*
        backend:
          serviceName: prod-user-reg-create-app
          servicePort: 8081
```
**CURL Output:**

```
suvenman@LUK-5CG9273QRF C:\Users\suvenman
$ curl -I -i -v  http://apps.mydomain.co.uk/user-reg/create/CreateUser
*   Trying 34.102.192.173...
* TCP_NODELAY set
* Connected to apps.mydomain.co.uk (34.102.192.173) port 80 (#0)
> HEAD /user-reg/create/CreateUser HTTP/1.1
> Host: apps.mydomain.co.uk
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 405
HTTP/1.1 405
< Allow: POST
Allow: POST
< Content-Type: application/json
Content-Type: application/json
< Transfer-Encoding: chunked
Transfer-Encoding: chunked
< Date: Wed, 27 Nov 2019 20:54:16 GMT
Date: Wed, 27 Nov 2019 20:54:16 GMT
< Via: 1.1 google
Via: 1.1 google

<
* Connection #0 to host apps.mydomain.co.uk left intact
```

```
suvenman@LUK-5CG9273QRF C:\Users\suvenman
$ curl -I -i -v  https://apps.mydomain.co.uk/user-reg/create/CreateUser
*   Trying 34.102.192.173...
* TCP_NODELAY set
* Connected to apps.mydomain.co.uk (34.102.192.173) port 443 (#0)
* schannel: SSL/TLS connection with apps.mydomain.co.uk port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 188 bytes...
* schannel: sent initial handshake data: sent 188 bytes
* schannel: SSL/TLS connection with apps.mydomain.co.uk port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with apps.mydomain.co.uk port 443 (step 2/3)
* schannel: encrypted data got 1845
* schannel: encrypted data buffer: offset 1845 length 4096
* schannel: sending next handshake data: sending 93 bytes...
* schannel: SSL/TLS connection with apps.mydomain.co.uk port 443 (step 2/3)
* schannel: encrypted data got 284
* schannel: encrypted data buffer: offset 284 length 4096
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with apps.mydomain.co.uk port 443 (step 3/3)
* schannel: stored credential handle in session cache
> HEAD /user-reg/create/CreateUser HTTP/1.1
> Host: apps.mydomain.co.uk
> User-Agent: curl/7.55.1
> Accept: */*
>
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 189
* schannel: encrypted data buffer: offset 189 length 103424
* schannel: decrypted data length: 160
* schannel: decrypted data added: 160
* schannel: decrypted data cached: offset 160 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 160 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 160
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 405
HTTP/1.1 405
< Allow: POST
Allow: POST
< Content-Type: application/json
Content-Type: application/json
< Transfer-Encoding: chunked
Transfer-Encoding: chunked
< Date: Wed, 27 Nov 2019 20:54:36 GMT
Date: Wed, 27 Nov 2019 20:54:36 GMT
< Via: 1.1 google
Via: 1.1 google
< Alt-Svc: clear
Alt-Svc: clear

<
* Connection #0 to host apps.mydomain.co.uk left intact
 
```

**Comment by git4suvendu** [comment]
I moved a few of the annotations to Config file. But still, it's not converting to HTTPS. Here are the details. I am running HAProxyTech.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fanout-ingress-haproxy
  namespace: xyz-product
  labels:                     # Labels that will be applied to this resource
    app: prod-user-reg-app
  annotations:
    kubernetes.io/ingress.global-static-ip-name: prod-reg-static-ip  #Defined in GCP platform. A Static IP needs to be created in the GCP.
 #   ingress.kubernetes.io/force-ssl-redirect: "true"
    haproxy.org/ingress.class: "haproxy"
    haproxy.org/load-balance: "leastconn"  #roundrobin
    haproxy.org/forwarded-for: "enabled"
 #   haproxy.org/ssl-certificate: "xyz-product/prod-tls-secret"
 #   haproxy.org/ssl-redirect: "ON"
 #   haproxy.org/ssl-redirect-code: "303"
spec:
  tls:
  - hosts:
    - mydomain.co.uk
    secretName: prod-tls-secret
  rules:
  - host: apps.mydomain.co.uk
    http:
      paths:
      - path: /user-reg/create/*
        backend:
          serviceName: prod-user-reg-create-app
          servicePort: 8081
```
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-configmap
  namespace: haproxy-controller
data:
    ssl-certificate: "xyz-product/prod-tls-secret"
    ssl-redirect: "ON"
    ssl-redirect-code: "303"
```
![image](https://user-images.githubusercontent.com/46852399/69762322-c900e380-1161-11ea-9aa5-b6100203a3c3.png)

Not sure what are these errors....

![image](https://user-images.githubusercontent.com/46852399/69762364-e33ac180-1161-11ea-9d83-355821289066.png)
