### ISSUE TITLE
Named service port set to "0" in backend name

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#13]
Hi,

Imagine I create the following service:
```
kind: Service
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
```
And the following ingress rule:
```
kind: Ingress
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: service1
          servicePort: http
```

Then the name of the relevant backend in HAProxy configuration would be ```<namespacename>-<servicename>-<port number>```

In the case of the service above, ```<port number>``` would be replaced by 0 which is pretty inaccurate and could lead to backend name overlap.
