### ISSUE TITLE
Host wildcard support

### ISSUE THREAD

**Issue by AdrienKuhn** [haproxytech/kubernetes-ingress#150]
Hi,

Does the `haproxy-ingress-controller` supports host wildcard ?

I can only access the default backend if I deploy the following ingress:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  namespace: my-namespace
spec:
  rules:
  - host: '*.mydomain.net'
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /
```

Thanks !
