### ISSUE TITLE
Priority of multiple paths?

### ISSUE THREAD

**Issue by dpgeekzero** [haproxytech/kubernetes-ingress#152]
Given the following ingress rules:

```
  - host: myhostname
    http:
      paths:
      - backend:
          serviceName: web
          servicePort: 80
        path: /
      - backend:
          serviceName: app-service
          servicePort: 8400
        path: /api
```

I always get the following config created

```
use_backend web-80 if { req.hdr(host) -i myhostname } { path_beg / }
use_backend app-service-8400 if { req.hdr(host) -i myhostname } { path_beg /api }
```

This results in me being unable to access my API service, as all traffic routes to the web service.  Am I doing something wrong here or is this just broken?

I noticed that the nginx controller simply sorts the paths by length in descending order, perhaps that would be a simple fix.
