### ISSUE TITLE
TCP services and SSL certificates

### ISSUE THREAD

**Issue by phanxen** [haproxytech/kubernetes-ingress#154]
Hi, I'm trying to configure HAproxy Ingress Controller to work TCP services.

After some trying and error, and reading [this](https://github.com/haproxytech/kubernetes-ingress/issues/148) post I could get something similar to what I expected. To be honest, I'm new to HAproxy Ingress Controller and have been using up to now HAproxy as HTTP/TCP proxy. Given some needs of our clients, we have to get our product running in Kubernetes.

So, the thing is, I cat get a TCP frontend to work without SSL, but I'm unable to get it working with SSL. The configmap for TCP services is like this (it's just a fragment of the YAML I have):

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-tcp-services
  namespace: haproxy-controller
data:
  "5003": "default/service1:35003"
  "7003": "default/service2:37003:::default/service2-ssl-cert"
```

When I apply the YAML file everything seems to work, but the pod running the controller gets filled with the following log messages:

```
2020/02/12 12:35:34 controller-monitor.go:120: 14: ERR transactionId=6a6f83c0-29ae-4a25-a025-a79072e88a2e 
msg="Proxy 'tcp-frontend-default-service2-37003---default-service2-ssl-cert-7003': unable to find required default_backend: 'default-service1-37003---default-service2-ssl-cert
```

From the point of view of HAproxy the error messages seems consistency, it can't create a frontend if its default backend doesn't exist. On the other hand, given both declarations of TCP services that I, I'd say something is about the secret I'm using. Te secret ```default/service2-ssl-cert```. I already tested creating this secret in ```haproxy-controller```namespace, but I got the error.

Any advice?
