### ISSUE TITLE
Provide support for ingress.kubernetes.io/rewrite-target annotation

### ISSUE THREAD

**Issue by safvankothawala** [haproxytech/kubernetes-ingress#174]
Please provide support for URL Rewriting using following annotation;
ingress.kubernetes.io/rewrite-target

For example, creating following ingress should work.

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          serviceName: test
          servicePort: 80
```
