### ISSUE TITLE
Feature request: initContainer for performance tuning

### ISSUE THREAD

**Issue by prometherion** [haproxytech/kubernetes-ingress#178]
_This is a feature request and quite similar to this [one](https://github.com/kubernetes/ingress-nginx/issues/1939) raised for the stable NGINX Ingress Controller_

Here at Namecheap, Inc. Cloud Team we're starting evaluating this Ingress Controller: we're running at scale several Ingress Controller classes, each one counting up to 20k virtual hosts.

According to our benchmarks, we used to do something like these to tune performances at _initContainer_ level (so before the Pod is able to serve traffic):

```bash
sysctl -w net.core.somaxconn=redacted
sysctl -w net.ipv4.ip_local_port_range="redacted redacted"
sysctl -w net.ipv4.tcp_rmem="redacted   redacted   redacted"
sysctl -w net.ipv4.tcp_wmem="redacted   redacted   redacted"
sysctl -w net.ipv4.tcp_slow_start_after_idle=redacted
sysctl -w net.ipv4.tcp_mtu_probing=redacted
sysctl -w net.netfilter.nf_conntrack_max=redacted
```

Would be great to add a new list of _Container_ key (`.controller.initContainers`) following the [core/v1 API spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#container-v1-core).

Implementing should be quite easy: just need to do `toYaml .Values.initContainers` with proper indent. Furthermore, is cross-compatible for both deployment strategies (_Deployment_ or _DaemonSet_).

## Desired values.yaml

```yaml
controller:
  name: controller
  image:
    repository: haproxytech/kubernetes-ingress    # can be changed to use CE or EE Controller images
    tag: "{{ .Chart.AppVersion }}"
    pullPolicy: IfNotPresent

  initContainers:
  - name: sysctl
    image: "busybox:1.31.1-musl"
    command:
    - /bin/sh
    - -xc
    - |-
      sysctl -w net.core.somaxconn=redacted
      sysctl -w net.ipv4.ip_local_port_range="redacted redacted"
      sysctl -w net.ipv4.tcp_rmem="redacted   redacted   redacted"
      sysctl -w net.ipv4.tcp_wmem="redacted   redacted   redacted"
      sysctl -w net.ipv4.tcp_slow_start_after_idle=redacted
      sysctl -w net.ipv4.tcp_mtu_probing=redacted
      sysctl -w net.netfilter.nf_conntrack_max=redacted
    securityContext:
      privileged: true
```
