### ISSUE TITLE
How to enable http2 support for backends

### ISSUE THREAD

**Issue by bsctl** [haproxytech/kubernetes-ingress#190]
Hello, it's my understanding that HTTP2 for backends is now supported starting from [HAProxy 1.9](https://www.haproxy.com/blog/haproxy-1-9-has-arrived/) thanks to the new Native HTTP Representation (HTX) implementation. 

However, I'm not able to get it working with the kubernetes ingress. 

Here an ingress exposing a simple http reply server which prints back the request and headers it receives:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace:
  name: test
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    # ingress.kubernetes.io/backend-protocol: "h2"  <--- this doesn't work
spec:
  rules:
  - host: test.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: test
          servicePort: 80
```

Accessing the service:

```
$ curl --http2 -k https://test.example.com
Server Name = "test-6ml9s"        <--- this is the name of the reply server pod
Client Addr = "10.0.124.81:58964"        <--- this is the internal address of HAProxy pod
Host = "test.example.com"
Method = "GET"
URL = "/"
Protocol = "HTTP/1.1"        <--- the reply server gets HTTP/1.1 from HAProxy pod
+++ Request Headers: +++
Header["Accept"] = ["*/*"]
Header["User-Agent"] = ["curl/7.54.0"]
Header["X-Forwarded-For"] = ["127.0.0.1"]
Header["X-Forwarded-Proto"] = ["https"]
```

I'm not able to find in the documentation any way to enable HTTP2 for the backends, is it supposed to work out-of-box (#38)?

HAProxy controller: `haproxytech/kubernetes-ingress:1.4.4`
HAProxy: `version 2.1.4 2020/04/02`

The controller is deployed on the worker nodes as daemonset with `hostNetwork: true`

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: router
  namespace: default
  labels:
    run: router
spec:
  minReadySeconds: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      run: haproxy-ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
    spec:
      serviceAccountName: router
      hostNetwork: true
      priorityClassName: system-node-critical
      # use toleration if a taint is set on the worker nodes
      # tolerations:
      # - key: node-role.kubernetes.io/infra
      #   effect: NoSchedule
      # nodeSelector:
      #   node-role.kubernetes.io/infra: ""
      containers:
      - name: haproxy-ingress
        image: haproxytech/kubernetes-ingress:1.4.4
        args:
          - --default-ssl-certificate=$(POD_NAMESPACE)/router-cert
          - --configmap=$(POD_NAMESPACE)/router-config
          - --default-backend-service=$(POD_NAMESPACE)/router-default-backend
          - --ingress.class=haproxy
          - --sync-period=3s
          - --log=debug
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 1042
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: stat
          containerPort: 1024
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```
Here the global Config Map

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: router-config
  namespace: default
  labels:
    run: router
data:
  # backend-protocol: "h2"    <--- this is not working
  check: "true"
  forwarded-for: "true"
  load-balance: "leastconn"
  maxconn: "2000"
  rate-limit: "false"
  rate-limit-expire: "30m"
  rate-limit-interval: "10s"
  rate-limit-size: "100k"
  servers-increment: "42"
  servers-increment-max-disabled: "66"
  #ssl-certificate: "router-cert"
  ssl-numproc: "1"
  ssl-redirect: "true"
  ssl-redirect-code: "302"
  timeout-http-request: "5s"
  timeout-connect: "5s"
  timeout-client: "50s"
  timeout-queue: "5s"
  timeout-server: "50s"
  timeout-http-keep-alive: "1m"
```
