### ISSUE TITLE
Separate HA config for separate rules/backends

### ISSUE THREAD

**Issue by tleish** [haproxytech/kubernetes-ingress#195]
When the HAProxy ingress contains multiple spec rules, can you configure different rules for each rule (backend)?

For example: 

```yaml

apiVersion: v1
kind: Service
metadata:
  name: http-svc
  labels:
    run: http-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: http-svc

--

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-ingress
spec:
  rules:
    - host: foo.com
      http:
        paths:
          - path: /app
            backend:
              serviceName: http-svc
              servicePort: 8080
          - path: /
            backend:
              serviceName: ingress-default-backend
              servicePort: 8080
```

In the example configuration, how would you configure `pod-maxconn` for `/app` (http-svc), but not for `/` (ingress-default-backend)?

**Comment by oktalz** [comment]
@tleish as you can see in https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation

there are quite few annotations that work on service level including `pod-maxconn`

so something like 

```
apiVersion: v1
kind: Service
metadata:
  name: http-svc
  labels:
    run: http-svc
  annotations:
    pod-maxconn: "1000"
 ...
```

is a way how you can define this for specific service
