### ISSUE TITLE
Support for send-proxy or send-proxy-v2 for TCP backend servers

### ISSUE THREAD

**Issue by prometherion** [haproxytech/kubernetes-ingress#199]
I got some backend servers served by TCP load balancing that are able to accept only PROXY protocol requests: although using the _ConfigMap_ formatting requested I'm not able to set the `send-proxy` or `send-proxy-v2` _Server_ option.

```
apiVersion: v1
data:
  "22": namespace/service:2222
kind: ConfigMap
metadata:
  name: tcp-configuration
  namespace: ingress
```

Actual rendered configuration:
```
backend namespace-service-2222
  mode tcp
  balance roundrobin                                                                                                                                                                                   
  server SRV_2hmVn 10.232.10.202:2222 weight 128
```

Could be great to add an additional parameter, something as the following:
```
apiVersion: v1
data:
  "22": namespace/service:2222::PROXY-V1
kind: ConfigMap
metadata:
  name: tcp-configuration
  namespace: ingress
```

To get it rendered in this way:
```
backend namespace-service-2222
  mode tcp
  balance roundrobin                                                                                                                                                                                   
  server SRV_2hmVn 10.232.10.202:2222 weight 128 send-proxy
```

Enums for the proxy options could be:
- `PROXY-V1` for `send-proxy`
- `PROXY-V2` for `send-proxy-v2`
