### ISSUE TITLE
Error when enabling rate-limiting

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#20]
I set the following YAML in my configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-ingress-external
  labels:
    app.kubernetes.io/name: haproxy-ingress
    helm.sh/chart: haproxy-ingress-0.1.0
    app.kubernetes.io/instance: external
    app.kubernetes.io/managed-by: Tiller
data:
  servers-increment: "10"
  servers-increment-max-disabled: "10"
  timeout-connect: "250ms"
  rate-limit: "ON"
  rate-limit-expire: "1m"
  rate-limit-interval: "10s"
  rate-limit-size: "100k"
```

And got the following error logs from the controller:
```
2019/07/05 09:03:08 controller-haproxy.go:140: 14: ERR transactionId=14481e20-00f6-4e3b-899c-03b26a747e67 
line=16 msg="unable to find table 'RateLimit' referenced in arg 1 of ACL keyword 'src_get_gpc0' in proxy 'http'."
line=17 msg="unable to find table 'RateLimit' referenced in arg 1 of ACL keyword 'src_inc_gpc0' in proxy 'http'."
line=18 msg="unable to find table 'RateLimit' referenced in arg 1 of ACL keyword 'src_http_req_rate' in proxy 'http'."
line=28 msg="unable to find table 'RateLimit' referenced in arg 1 of ACL keyword 'src_get_gpc0' in proxy 'https'."
line=29 msg="unable to find table 'RateLimit' referenced in arg 1 of ACL keyword 'src_inc_gpc0' in proxy 'https'."
line=30 msg="unable to find table 'RateLimit' referenced in arg 1 of ACL keyword 'src_http_req_rate' in proxy 'https'."
```
