### ISSUE TITLE
HAProxy doesn't bind to HTTPS if a TLS Secret is empty

### ISSUE THREAD

**Issue by prometherion** [haproxytech/kubernetes-ingress#212]
This is pretty an edge case but can happen when dealing as a Platform as a Service.

Let's imagine I got my Ingress as following:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-42e8a
  namespace: default
spec:
  rules:
  - host: redacted.tld
    http:
      paths:
      - backend:
          serviceName: svc-42e8a
          servicePort: 80
        path: /
  - host: redacted
    http:
      paths:
      - backend:
          serviceName: svc-42e8a
          servicePort: 80
        path: /
  tls:
  - hosts:
    - redacted.tld
    secretName: secret-42e8a
```

...but the secret is empty, due to an error:

```yaml
apiVersion: v1
data:
  tls.crt: ""
  tls.key: ""
kind: Secret
metadata:
  name: secret-42e8a
  namespace: default
type: Opaque
```

From Ingress Controller logs I can see the configuration reload hasn't been processed:

```
2020/07/01 13:51:04 ERROR   controller.go:197 14: ERR transactionId=00d2c69c-649e-49b0-8e41-f2420132ebbd
line=17545 msg="'bind 0.0.0.0:443' :"
line=17546 msg="'bind :::443' :"
2020/07/01 13:51:04 ERROR   monitor.go:140 14: ERR transactionId=00d2c69c-649e-49b0-8e41-f2420132ebbd
line=17545 msg="'bind 0.0.0.0:443' :"
line=17546 msg="'bind :::443' :"
```

Validating the failed configuration, I see the error:
```
# kubectl exec ... -- haproxy -c -f /tmp/haproxy/failed/haproxy.cfg.00d2c69c-649e-49b0-8e41-f2420132ebbd
[ALERT] 182/135527 (54) : parsing [/tmp/haproxy/failed/haproxy.cfg.00d2c69c-649e-49b0-8e41-f2420132ebbd:17545] : 'bind 0.0.0.0:443' : 
  unable to load private key from file '/etc/haproxy/certs/ingress-42e8a_default_secret-42e8a.pem.rsa'.
[ALERT] 182/135527 (54) : parsing [/tmp/haproxy/failed/haproxy.cfg.00d2c69c-649e-49b0-8e41-f2420132ebbd:17546] : 'bind :::443' : 
  unable to load private key from file '/etc/haproxy/certs/ingress-42e8a_default_secret-42e8a.pem.rsa'.
[ALERT] 182/135527 (54) : Error(s) found in configuration file : /tmp/haproxy/failed/haproxy.cfg.00d2c69c-649e-49b0-8e41-f2420132ebbd
[ALERT] 182/135527 (54) : Fatal errors found in configuration.
```

# What I'm expecting

The non-well-formed certificates should be ignored, printing a `warn || warning` logline and serving the ingress as HTTP (or non-serving it at all)
