### ISSUE TITLE
armv7 support?

### ISSUE THREAD

**Issue by adrianchifor** [haproxytech/kubernetes-ingress#222]
I'm trying to run the haproxy ingress on a Raspberry Pi k8s cluster which is armv7 but the only architecture I see available in the Docker builds is amd64. Any plans to support armv7 (32bit and 64bit)?

**Comment by TiemenSch** [comment]
I'm currently trying out building a ARM compatible image myself: 
https://gitlab.com/Tiemen/haproxy-arm64

Will report back if it works with the Helm chart

**Comment by TiemenSch** [comment]
I got it to work, but for the Helm chart you would need to redefine the ``default-http-backend`` image, too. (that one defaults, too, defaults to AMD64).

On K3s, I added it using the following:
``kubectl create ns haproxy-controller``

And applying the Helmchart with:
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: haproxy
  namespace: kube-system
spec:
  repo: https://haproxytech.github.io/helm-charts
  chart: kubernetes-ingress
  targetNamespace: haproxy-controller
  valuesContent: |-
    controller:
      image:
        repository: "registry.gitlab.com/tiemen/haproxy-arm64"
        tag: "latest"
        pullPolicy: Always
    defaultBackend:
      image:
        repository: k8s.gcr.io/defaultbackend-arm64
```
