### ISSUE TITLE
SNI Content Switching

### ISSUE THREAD

**Issue by alexgeek** [haproxytech/kubernetes-ingress#224]
Hi there,

I have a need to redirect to internal plasticscm servers based on hostname (from SNI).

I setup a haproxy pod (normal haproxy not the controller) and used the following configuration:

```
# Adjust the timeout to your needs
defaults
  timeout client 30s
  timeout server 30s
  timeout connect 5s
  log stdout format raw local0

# Single VIP
frontend ft_ssl_vip
  bind *:8088
  mode tcp

  tcp-request inspect-delay 5s
  tcp-request content accept if { req_ssl_hello_type 1 }

  default_backend bk_ssl_default

# Using SNI to take routing decision
backend bk_ssl_default
  mode tcp

  # replace plastic.example.com with desired hostname
  acl application_1 req_ssl_sni -i plastic.example.com

  use-server server1 if application_1

  option ssl-hello-chk
  # replace XXX.XXX.XXX.XXX with internal ip
  server server1 plastic.plastic-namespace.svc.cluster.local:8088 check
```

This works correctly and will I can connect to the server which is fantastic as I keep running low on external IPs as I needed to use a loadbalancer per plastic server before. 

Is this sort of configuration currently possible using the haproxy controller? Possibly with some fairly complex annotations?

**Comment by Mo3m3n** [comment]
Hi 
I suppose the traffic coming on 8088 is ssl traffic, otherwise this don't make much sense for me.
Yes can do the same with controller using the annotation [ssl-passthrough](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#https): "true".
This will make HAProxy route traffic based on SNI (instead of Host header).

**Comment by alexgeek** [comment]
> Hi
> I suppose the traffic coming on 8088 is ssl traffic, otherwise this don't make much sense for me.
> Yes can do the same with controller using the annotation [ssl-passthrough](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#https): "true".
> This will make HAProxy route traffic based on SNI (instead of Host header).

Thanks just tried that but it seems like the controller is hardcoded to only listen on 443 for ssl-passthrough.
Is there anyway around that? Plastic doesn't let me connect using port 443.

**Comment by alexgeek** [comment]
For reference I'm looking at [this line](https://github.com/haproxytech/kubernetes-ingress/blob/baccca322bb30ed126d81638dd42a5a418085595/controller/https.go#L159).

**Comment by Mo3m3n** [comment]
Currently ingress controller will only make haproxy listen on 443
But this should not be an issue because since in Kubernetes applications are exposed via service so you can have something like this in the service manifest:
```
  ports:
    - name: https
      port: 8088
      protocol: TCP
      targetPort: https
``` 
Does this help ?

**Comment by alexgeek** [comment]
> Currently ingress controller will only make haproxy listen on 443
> But this should not be an issue since in Kubernetes applications are exposed via services so you can have something like this in the service manifest:
> 
> ```
>   ports:
>     - name: https
>       port: 8088
>       protocol: TCP
>       targetPort: https
> ```
> 
> Does this help ?

Oh I think I see, listen on the loadbalancer and redirect to 443? That's a good idea will try now.

**Comment by Mo3m3n** [comment]
This may or may not work depending on how you deploy the ingress controller (service type) .

**Comment by alexgeek** [comment]
Hmm I was hopeful that would work but I get the following error and a timeout on my client:

```
127.0.0.1:38242 [03/Aug/2020:16:07:24.317] https/bind_1: SSL handshake failure
```

That was with these helm values:

```
---
controller:
  logging:
    level: debug
    traffic:
      address: "stdout"
      format: "raw"
      facility: "daemon"
  service:
    tcpPorts:
      - name: plastic
        port: 8087
        targetPort: https
      - name: plastic-ssl
        port: 8088
        targetPort: https
    type: LoadBalancer
```
and this ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: haproxy-ingress-plastic
  namespace: dev-ndw-002
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: dev-ndw-002.haproxy-staging.acuteart.studio
    http:
      paths:
      - backend:
          serviceName: plastic-secure
          servicePort: 8088
```

Which results in this config:

```
# _version=4
# HAProxy Technologies
# https://www.haproxy.com/
# this file is not meant to be changed directly
# it is under haproxy ingress controller management

global
  master-worker
  pidfile /var/run/haproxy.pid
  stats socket /var/run/haproxy-runtime-api.sock level admin expose-fd listeners
  stats timeout 1m
  tune.ssl.default-dh-param 2048
  ssl-default-bind-options no-sslv3 no-tls-tickets no-tlsv10
  ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK
  log stdout format raw daemon
  server-state-file global
  server-state-base /var/state/haproxy/

defaults
  log global
  log-format '%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs "%HM %[var(txn.base)] %HV"'
  option redispatch
  option dontlognull
  option http-keep-alive
  timeout http-request 5s
  timeout connect 5s
  timeout client 50s
  timeout queue 5s
  timeout server 50s
  timeout tunnel 1h
  timeout http-keep-alive 1m
  load-server-state-from-file global

frontend healthz
  mode http
  bind 0.0.0.0:1042 name healtz_1
  monitor-uri /healthz
  option dontlog-normal

frontend http
  mode http
  bind 0.0.0.0:80 name bind_1
  bind :::80 v4v6 name bind_2
  http-request set-var(txn.base) base
  http-request set-var(txn.host) req.hdr(Host)
  default_backend haproxy-haproxy-ingress-kubernetes-ingress-default-backend-8080

frontend https
  mode http
  bind 127.0.0.1:8443 name bind_1 crt /etc/haproxy/certs ssl alpn h2,http/1.1
  http-request set-var(txn.base) base
  http-request set-var(txn.host) req.hdr(Host)
  http-request set-header X-Forwarded-Proto https if { ssl_fc }
  default_backend haproxy-haproxy-ingress-kubernetes-ingress-default-backend-8080

frontend ssl
  mode tcp
  bind 0.0.0.0:443 name bind_1
  bind :::443 name bind_2 v4v6
  log-format '%ci:%cp [%t] %ft %b/%s %Tw/%Tc/%Tt %B %ts %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %[var(sess.sni)]'
  tcp-request inspect-delay 5000
  tcp-request content set-var(sess.sni) req_ssl_sni
  tcp-request content accept if { req_ssl_hello_type 1 }
  use_backend dev-ndw-002-plastic-secure-8088 if { req_ssl_sni -i dev-ndw-002.haproxy-staging.acuteart.studio }
  default_backend https

frontend stats
  mode http
  bind *:1024
  stats enable
  stats uri /
  stats refresh 10s
  http-request use-service prometheus-exporter if { path /metrics }

backend dev-ndw-002-plastic-secure-8088
  mode tcp
  balance roundrobin
  server SRV_s9iS2 127.0.0.1:8088 disabled check weight 128
  server SRV_YiLKI 127.0.0.1:8088 disabled check weight 128
  server SRV_1WPqh 127.0.0.1:8088 disabled check weight 128
  server SRV_S07Z0 127.0.0.1:8088 disabled check weight 128
  server SRV_j9wVb 127.0.0.1:8088 disabled check weight 128
  server SRV_xaDk6 127.0.0.1:8088 disabled check weight 128
  server SRV_1KLNz 10.32.1.73:8088 check weight 128
  server SRV_nWbAm 127.0.0.1:8088 disabled check weight 128
  server SRV_fSV9B 127.0.0.1:8088 disabled check weight 128
  server SRV_wgD9h 127.0.0.1:8088 disabled check weight 128
  server SRV_uFWo7 127.0.0.1:8088 disabled check weight 128
  server SRV_hrGLP 127.0.0.1:8088 disabled check weight 128
  server SRV_QSQBj 127.0.0.1:8088 disabled check weight 128
  server SRV_ajY11 127.0.0.1:8088 disabled check weight 128
  server SRV_WfYJk 127.0.0.1:8088 disabled check weight 128
  server SRV_IPWst 127.0.0.1:8088 disabled check weight 128
  server SRV_hbvYl 127.0.0.1:8088 disabled check weight 128
  server SRV_1EWeM 127.0.0.1:8088 disabled check weight 128
  server SRV_vdSIB 127.0.0.1:8088 disabled check weight 128
  server SRV_WZiU6 127.0.0.1:8088 disabled check weight 128
  server SRV_2CQE2 127.0.0.1:8088 disabled check weight 128
  server SRV_WMGil 127.0.0.1:8088 disabled check weight 128
  server SRV_DZrss 127.0.0.1:8088 disabled check weight 128
  server SRV_rBKEr 127.0.0.1:8088 disabled check weight 128
  server SRV_sWXA5 127.0.0.1:8088 disabled check weight 128
  server SRV_DfoGN 127.0.0.1:8088 disabled check weight 128
  server SRV_bMGoa 127.0.0.1:8088 disabled check weight 128
  server SRV_lrqfj 127.0.0.1:8088 disabled check weight 128
  server SRV_1jGBq 127.0.0.1:8088 disabled check weight 128
  server SRV_8xGkZ 127.0.0.1:8088 disabled check weight 128
  server SRV_Gc3x1 127.0.0.1:8088 disabled check weight 128
  server SRV_baNmh 127.0.0.1:8088 disabled check weight 128
  server SRV_nU9Zx 127.0.0.1:8088 disabled check weight 128
  server SRV_GWlwV 127.0.0.1:8088 disabled check weight 128
  server SRV_xaHuF 127.0.0.1:8088 disabled check weight 128
  server SRV_JAIJp 127.0.0.1:8088 disabled check weight 128
  server SRV_a7d8J 127.0.0.1:8088 disabled check weight 128
  server SRV_3pAcH 127.0.0.1:8088 disabled check weight 128
  server SRV_XiR8L 127.0.0.1:8088 disabled check weight 128
  server SRV_GcFer 127.0.0.1:8088 disabled check weight 128
  server SRV_DQ1vL 127.0.0.1:8088 disabled check weight 128
  server SRV_bhOo0 127.0.0.1:8088 disabled check weight 128

backend haproxy-haproxy-ingress-kubernetes-ingress-default-backend-8080
  mode http
  balance roundrobin
  option forwardfor
  server SRV_h0t7r 127.0.0.1:8080 disabled check weight 128
  server SRV_21jOK 127.0.0.1:8080 disabled check weight 128
  server SRV_1Dy5I 127.0.0.1:8080 disabled check weight 128
  server SRV_egVFw 127.0.0.1:8080 disabled check weight 128
  server SRV_9QuLK 127.0.0.1:8080 disabled check weight 128
  server SRV_MUckg 127.0.0.1:8080 disabled check weight 128
  server SRV_ZXStf 127.0.0.1:8080 disabled check weight 128
  server SRV_WBHcq 127.0.0.1:8080 disabled check weight 128
  server SRV_NKKGt 127.0.0.1:8080 disabled check weight 128
  server SRV_6mytf 127.0.0.1:8080 disabled check weight 128
  server SRV_4WMOa 10.32.1.55:8080 check weight 128
  server SRV_MN09b 127.0.0.1:8080 disabled check weight 128
  server SRV_kp3Mz 127.0.0.1:8080 disabled check weight 128
  server SRV_OQLRD 127.0.0.1:8080 disabled check weight 128
  server SRV_OPGVW 127.0.0.1:8080 disabled check weight 128
  server SRV_kBJwd 127.0.0.1:8080 disabled check weight 128
  server SRV_mKxpZ 127.0.0.1:8080 disabled check weight 128
  server SRV_qcykG 127.0.0.1:8080 disabled check weight 128
  server SRV_QHGxW 127.0.0.1:8080 disabled check weight 128
  server SRV_nAXsL 127.0.0.1:8080 disabled check weight 128
  server SRV_Wu73x 127.0.0.1:8080 disabled check weight 128
  server SRV_mRiGd 127.0.0.1:8080 disabled check weight 128
  server SRV_FiRff 127.0.0.1:8080 disabled check weight 128
  server SRV_ogPv9 127.0.0.1:8080 disabled check weight 128
  server SRV_p9o5z 127.0.0.1:8080 disabled check weight 128
  server SRV_5hlyz 127.0.0.1:8080 disabled check weight 128
  server SRV_FjRR7 127.0.0.1:8080 disabled check weight 128
  server SRV_2FZIq 127.0.0.1:8080 disabled check weight 128
  server SRV_0f1q1 127.0.0.1:8080 disabled check weight 128
  server SRV_FcAqU 127.0.0.1:8080 disabled check weight 128
  server SRV_HhiJt 127.0.0.1:8080 disabled check weight 128
  server SRV_uqthb 127.0.0.1:8080 disabled check weight 128
  server SRV_HUDKb 127.0.0.1:8080 disabled check weight 128
  server SRV_40OK2 127.0.0.1:8080 disabled check weight 128
  server SRV_BmVoC 127.0.0.1:8080 disabled check weight 128
  server SRV_BRm8C 127.0.0.1:8080 disabled check weight 128
  server SRV_XITUa 127.0.0.1:8080 disabled check weight 128
  server SRV_SqAgV 127.0.0.1:8080 disabled check weight 128
  server SRV_w4KCO 127.0.0.1:8080 disabled check weight 128
  server SRV_qFrxA 127.0.0.1:8080 disabled check weight 128
  server SRV_mNWhb 127.0.0.1:8080 disabled check weight 128
  server SRV_dJQ4X 127.0.0.1:8080 disabled check weight 128

backend https
  mode tcp
  server https 127.0.0.1:8443
```

Any idea?

**Comment by Mo3m3n** [comment]
That  `tcpPorts` value of the Helm is irrelevant here.
This is used for when using the controller with [tcp services](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md)
Sorry for the confusion we should document this better
Although 'ssl-passthrough' is also based on a tcp frontend but it is a different use case here.
Can you tell what the exact URL you are using to test this on the client side ?

**Comment by alexgeek** [comment]
I think it has the desired effect though looking at the service?

```
spec:
    clusterIP: 10.225.11.39
    externalTrafficPolicy: Cluster
    ports:
    - name: http
      nodePort: 30597
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      nodePort: 30824
      port: 443
      protocol: TCP
      targetPort: https
    - name: stat
      nodePort: 32061
      port: 1024
      protocol: TCP
      targetPort: stat
    - name: plastic-tcp
      nodePort: 32349
      port: 8087
      protocol: TCP
      targetPort: https
    - name: plastic-ssl-tcp
      nodePort: 32317
      port: 8088
      protocol: TCP
      targetPort: https
```

I guess I should be using ports/enablePorts/targetPorts instead though?

The url is: dev-ndw-002.haproxy-staging.acuteart.studio
