### ISSUE TITLE
'ssl-passthrough' annotation breaks all present http mode ingresses

### ISSUE THREAD

**Issue by punkprzemo** [haproxytech/kubernetes-ingress#226]
Is there any way to disable the possibility to add some type of haproxy ingress annotations? Below is explanation what i mean.
I have a multiuser kubernetes cluster. HAProxy ingress is used in http mode. If any user in any namespace set `ssl-passthrough: true` annotation on his service or ingress object than all cluster http ingresses stops working !
From my perspective it's huge security issue because any user who can crate services or ingress objects in the cluster can break whole http mode  ingress-controller  traffic.

I can see that documentation says that annotation `ssl-passthrough`  makes unavailable a number of the controller annotations (requiring HTTP mode)
```
- Annotation `ssl-passthrough`
  - by default ssl-passthrough is disabled.
	- Make HAProxy send TLS traffic directly to the backend instead of offloading it.
	- Traffic is proxied in TCP mode which makes unavailable a number of the controller annotations (requiring HTTP mode).
```
But how can I protect http ingresses from being break by this  `ssl-passthrough:true ` annotation set anywhere in the cluster  by mistake or unaware user or attacker?

**Comment by Mo3m3n** [comment]
Hi I have tried reproducing this with latest controller version `1.4.6` at the time of writing and configured two ingresses one with `ssl-passthrough` enabled and the other not enabled and still have them both work correctly which means I get the expected http/s reponses.
Can you describe your environment (controller version, configmap, ingress objects) and tell us what you mean by 
>http ingresses stops working

Thanks

**Comment by punkprzemo** [comment]
By `http ingresses stops working` I mean `http mode`  ingress backends stop working. (ssl-passthrough when enabled should proxy traffic in TCP mode) 

I'm using `haproxytech/kubernetes-ingress:1.4.6`
Kubernetes `1.18.3`
Ingress controller  is installed using helm Chart. Ingress controller container is started with below options:
```
spec:
      containers:
      - args:
        - --default-ssl-certificate=kube-ingress/ingress-wildcard-cert
        - --configmap=kube-ingress/ingress-private-kubernetes-ingress
        - --default-backend-service=kube-ingress/ingress-private-kubernetes-ingress-default-backend
        - --log=info
```
And as a hostPort pod
```
ports:
        - containerPort: 1042
          hostPort: 1042
          name: healthz
          protocol: TCP
        - containerPort: 80
          hostPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          name: https
          protocol: TCP
        - containerPort: 1024
          hostPort: 1024
          name: stat
          protocol: TCP
```
Below is example of working  `http-mode` ingress I have:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami
  namespace: whoami
spec:
  rules:
  - host: whoami.mydomain.internal
    http:
      paths:
      - backend:
          serviceName: whoami
          servicePort: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - whoami.mydomain.internal
```
Then i create ssl-passthrough enabled ingress.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
  name: dummy
spec:
  rules:
  - host: dummy-ssl-passthrough.mydomain.internal
    http:
      paths:
      - backend:
          serviceName: dummy-ssl-passthrough
          servicePort: 666
        path: /
```

After creation of ssl-passthrough ingress the ingress from first example `https://whoami.mydomain.internal` returns below error in chrome browser
```
This site can’t provide a secure connectionwhoami.apps.dap.pl.ing.net sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```
Interesting part how ingress controller configuration is changing:


Before adding any `ssl-passthrough` enabled ingress i have below in `/etc/haproxy/haproxy.cfg`
```
frontend https 
  mode http
  bind 0.0.0.0:443 name bind_1 crt /etc/haproxy/certs ssl alpn h2,http/1.1
  bind :::443 name bind_2 crt /etc/haproxy/certs ssl v4v6 alpn h2,http/1.1
...
```

After adding any `ssl-passthrough` enabled ingress i have below in `/etc/haproxy/haproxy.cfg`

```
frontend https 
  mode http
  bind 127.0.0.1:8443 name bind_1
  http-request set-var(txn.host) req.hdr(Host)
  http-request set-var(txn.base) base
  http-request set-header X-Forwarded-Proto https if { ssl_fc }
  use_backend whoami-whoami-80 if { req.hdr(host),field(1,:) -i whoami.mydomain.internal } { path_beg / }
  use_backend vault-vault-ui-8200 if { req.hdr(host),field(1,:) -i vault.mydomain.internal } { path_beg / }
  default_backend kube-ingress-ingress-private-kubernetes-ingress-default-backend-8080

frontend ssl 
  mode tcp
  bind 0.0.0.0:443 name bind_1
  bind :::443 name bind_2 v4v6
  log-format '%ci:%cp [%t] %ft %b/%s %Tw/%Tc/%Tt %B %ts %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %[var(sess.sni)]'
  tcp-request inspect-delay 5000
  tcp-request content set-var(sess.sni) req_ssl_sni
  tcp-request content accept if { req_ssl_hello_type 1 }
  use_backend kube-ingress-dummy-ssl-passthrough-666 if { req_ssl_sni -i dummy-ssl-passthrough.mydomain.internal } 
  default_backend https

```

frontend `http mode` port is changing from 0.0.0.0:443 to 127.0.0.1:8443 ...

Regards
Przemek
