### ISSUE TITLE
haproxy-ingress to pod ip instead of service ip - baremetal / cri-o

### ISSUE THREAD

**Issue by kallisti5** [haproxytech/kubernetes-ingress#237]
Having an odd issue where the haproxy-ingress is sending requests to the pod ip addresses instead of the service ip addesses.

*Environment*
* Kubernetes 1.19
* cri-o 1.19
* calico (and flannel)
* coredns

Better details below...

**Comment by kallisti5** [comment]
haproxy logs
[haproxy-logs.txt](https://github.com/haproxytech/kubernetes-ingress/files/5403108/haproxy-logs.txt)

**Comment by kallisti5** [comment]
![l4timeout](https://user-images.githubusercontent.com/100110/96490298-3c8e6200-1206-11eb-9c29-22e625f03fab.png)

**Comment by kallisti5** [comment]
Ok.  I've done some research on this one.  It appears haproxy is getting the pod ip's instead of the service ip's.

```
# kubectl get all -o wide
NAME                                           READY   STATUS    RESTARTS   AGE     IP            NODE                  NOMINATED NODE   READINESS GATES
pod/haikeuken-5c8d474588-ltpxj                 1/1     Running   0          8m11s   10.244.0.25   k8sdal1terarocketio   <none>           <none>
pod/haproxy-ingress-599569f95c-xv2z4           1/1     Running   0          8m47s   10.244.0.24   k8sdal1terarocketio   <none>           <none>
pod/ingress-default-backend-78f5cc7d4c-hcr6l   1/1     Running   0          8m47s   10.244.0.23   k8sdal1terarocketio   <none>           <none>
```

```
NAME                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                AGE     SELECTOR
service/haikeuken-service         ClusterIP   10.111.96.163    <none>        3000/TCP                               8m11s   app=haikeuken
service/haproxy-ingress           NodePort    10.100.166.86    <none>        80:80/TCP,443:443/TCP,1024:26521/TCP   8m47s   run=haproxy-ingress
service/ingress-default-backend   ClusterIP   10.102.237.136   <none>        8080/TCP                               8m47s   run=ingress-default-backend
```


```
kubectl exec -it pod/haproxy-ingress-599569f95c-xv2z4 -- cat /etc/haproxy/haproxy.cfg | grep -v disabled

backend default-haikeuken-service-3000 
  mode http
  balance roundrobin
  option forwardfor
  http-request replace-path (.*) /
  server SRV_CGPSB 10.244.0.25:3000 check weight 128

backend default-ingress-default-backend-8080 
  mode http
  balance roundrobin
  option forwardfor
  server SRV_8EMUg 10.244.0.23:8080 check weight 128
```


Application deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haikeuken
  labels:
    app: haikeuken
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haikeuken
  template:
    metadata:
      labels:
        app: haikeuken
    spec:
      containers:
      - name: haikeuken
        image: quay.io/terarocket/haikeuken
        env:
        - name: DATABASE_URL
          value: "postgresql://postgresadmin:XXX@postgres:5432/haikeuken"
        - name: SECRET_KEY_BASE
          value: "XXX"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: haikeuken-service
spec:
  selector:
    app: haikeuken
  ports:
    - protocol: TCP
      port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haikeuken-ingress
  annotations:
    haproxy.org/path-rewrite: "/"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: haikeuken-service
            port:
              number: 3000
```
