### ISSUE TITLE
haproxy ingress path-rewrite issue with v1.4.9

### ISSUE THREAD

**Issue by rxn98** [haproxytech/kubernetes-ingress#243]
# HAProxy path-rewrite issue in 1.4.9
Hi Team,

After upgrading to kubernetes-ingress (haproxy) to *1.4.9* we are facing issue with path-rewrite.

https://github.com/haproxytech/kubernetes-ingress/commit/3187c34a0d6e03646fb55440cdb9a06fa21e0514

##### Problem
Can't control path-rewrite in kubernetes service level

##### Ingress

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: haproxy-ingress
  namespace: test
  annotations:
    kubernetes.io/ingress.class: "haproxy"
spec:
  rules:
    - host: test.example.com
      http:
        paths:
          - path: /test/service1/
            backend:
              serviceName: serviceA
              servicePort: 443
          - path: /test/service2/
            backend:
              serviceName: serviceB
              servicePort: 443
```
##### Service 1
```
apiVersion: v1
kind: Service
metadata:
  name: serviceA
  annotations:
    haproxy.org/path-rewrite: /test/service1/(.*) /service1/\1
  labels:
    app.kubernetes.io/name: testApp1
    app.kubernetes.io/instance: testApp1
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      name: testA
      targetPort: testA
```
##### Service 2
```
apiVersion: v1
kind: Service
metadata:
  name: serviceB
  annotations:
    haproxy.org/path-rewrite: /test/service2/(.*) /service2/\1
  labels:
    app.kubernetes.io/name: testApp2
    app.kubernetes.io/instance: testApp2
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      name: testB
      targetPort: testB
```

Calling service <domain>/test/service1 or <domain>/test/service2 results 404 error

Moving path-rewrite to frontend controller limiting as to have only one path-rewrite and create multiple ingress controllers.

We are having many routes which comes with same context path. Any idea or solution to overcome this situation is much appreciated or can this considered as a bug ?
