### ISSUE TITLE
Abnormal CPU/Memory usage

### ISSUE THREAD

**Issue by punkprzemo** [haproxytech/kubernetes-ingress#245]
Hello,

We have a problem with CPU/memory usage of the haproxytech kubernetes ingress controller.
We are using dev version which is  from August. 
```
HAProxy Ingress Controller v1.4.5 1b81eb6.dev
Build from: https://mo3m3n@github.com/haproxytech/kubernetes-ingress
Build date: 2020-08-18T17:30:15
```
Ingress controller is running on physical server with 40CPU cores and 64 GB of RAM memory. Ingress controller didn't have resource limits set till today.
Please see below graph with CPU/memory usage from last 10 days. This bigest CPU/memory usage is single instance of haproxytech ingress controller
![haproxy-ingress-private-cpu-mem](https://user-images.githubusercontent.com/36777025/98733363-b4345480-23a0-11eb-819c-be68c13ba5f8.png)
This single controller instance is going to machine CPU limits quite quickly during a day when workload is bigger.

Today's morning I have set resource limit for pod to 4CPU/16Gi memory.
Now cpu/mem usage graph looks like below:
![haproxy-ingress-private-with-limit](https://user-images.githubusercontent.com/36777025/98734572-72a4a900-23a2-11eb-9779-cbea654967a8.png)
So with limits in place instance is going quite quickly to the CPU limit  but after some time liveness probes starts failing and  the pod is restarted  `Unhealthy   pod/ingress-private-kubernetes-ingress-nj6cf   Liveness probe failed: Get http://192.168.182.104:1042/healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

Today we have already 13 restarts which is visible on today's graph. 

Kubernetes cluster is 1.18.9 with currently around 400 ingress objects.
The reason why we use dev version of haproxy ingress-controller is [`config-snippet`](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#config-snippet-1) option which is currently only available  in `dev` version.
The ingress controller is installed from helm chart (v1.6.2 but with dev image) as daemonset with hostNetwork.
For helm installation below custom values are used:
```
controller:
  daemonset:
    hostPorts:
      http: 80
      https: 443
      stat: 1024
      healthz: 1042
    useHostPort: true
    useHostNetwork: true
  kind: DaemonSet
  containerPort:
    http: 80
    https: 443
    stat: 1024
    healthz: 1042
  image:
    pullPolicy: IfNotPresent
    repository: private.repo.internal/docker-io/haproxytech/kubernetes-ingress
  nodeSelector:
    ingress-private: haproxy
  podLabels:
    ingress-private: haproxy
  tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
  service:
    type: ClusterIP
  extraArgs:
  defaultTLSSecret:
    enabled: true
    secret: ingress-wildcard-cert
  config:
    blacklist: 192.168.13.225/32
    whitelist: 192.168.182.0/24
defaultBackend:
  image:
    pullPolicy: IfNotPresent
    repository: private.repo.internal/k8s-gcr-io/defaultbackend-amd64
    runAsUser: 65534
  name: default-backend
  nodeSelector: 
    ingress-private: haproxy
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  podLabels:
    ingress-private: haproxy-default-backend
  replicaCount: 2
podSecurityPolicy:
  annotations: {}
  enabled: true
rbac:
  create: true
serviceAccount:
  create: true
  name: ingress-private
```
I have seen #191 #216 and #217 and it seems that the fix from #217  is included in dev version we use.
Can you have a look and advice on the issue we have?

Regards
