### ISSUE TITLE
BUG: svc not used when missing port.name

### ISSUE THREAD

**Issue by Frankkkkk** [haproxytech/kubernetes-ingress#280]
Hi,

There seems to be a bug with commit 3649d4c1 

Indeed, ingresses that point to a service with a nameless port are not installed.

My ingress:
```
  spec:
    rules:
    - host: 9d621b7afa094ac8bd9a30714068a95e.ch
      http:
        paths:
        - backend:
            serviceName: php74-www
            servicePort: 80
          pathType: ImplementationSpecific
```

the svc:
```
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
```

and the logs:
```
2021/03/02 09:26:12 ERROR   controller.go:244 ingress 03163af12b65466ba09d9b7309c6a20d/lamp: service php74-www: no service port matching '80'
```

and when I add a name to the svc, it works again:
```
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
```

However, reading the doc, it seems that having a name is not mandatory if there's only one port on the SVC:
```
   name	<string>
     The name of this port within the service. This must be a DNS_LABEL. All
     ports within a ServiceSpec must have unique names. When considering the
     endpoints for a Service, this must match the 'name' field in the
     EndpointPort. Optional if only one ServicePort is defined on this service.
```

Cheers
