### ISSUE TITLE
How to use a custom certificate with TCP ssl offloading ?

### ISSUE THREAD

**Issue by ahmadki** [haproxytech/kubernetes-ingress#283]
Thank you for the amazing work in enabling ssl offloading for TCP services. I was able to secure a MQTT endpoint in 2 simple steps (I'm using the kubernetes-ingress helm chart):

1. created a `ingress/tcp-services` config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress
data:
  1883:
    mqtt/mqtt-svc:1883:ssl
````
2. set the following values in my helm install:
```
controller:
    extraArgs:
        - --configmap-tcp-services=ingress/tcp-services
    service:
        tcpPorts:
            - name: mqtt
              protocol: TCP
              port: 1883
              targetPort: 1883
```

However, the above will use the default tls certificate and the documentation don't mention how to load a custom certificate from an existing secrete.

I tried some of the formats from https://haproxy-ingress.github.io/docs/configuration/command-line/#tcp-services-configmap but nothing worked.

**Comment by ahmadki** [comment]
One solution I found is to add a new ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mqtt-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: haproxy
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mqtt-svc
                port:
                  number: 1883
  tls:
    - secretName: mqtt-tls
      hosts:
        - mqtt.example.com
```

but shouldn't ingress be reserved for HTTP ?
