### ISSUE TITLE
Ingress controller not listening on port 80/443

### ISSUE THREAD

**Issue by chrispage1** [haproxytech/kubernetes-ingress#29]
Hi,

So I'm having issues implementing the HAProxy ingress controller. I thought that Ingress controllers were meant to listen on ports 80 & 443 - however, these aren't exposed on the nodes.

If I list out the services I can get the node ports -

````
[root@master server]$ kubectl get svc -o wide -n haproxy-controller
NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                     AGE   SELECTOR
haproxy-ingress           NodePort    10.102.75.131   <none>        80:30990/TCP,443:30486/TCP,1024:31359/TCP   27m   run=haproxy-ingress
ingress-default-backend   ClusterIP   10.104.89.140   <none>        8080/TCP                                    27m   run=ingress-default-backend
````

So from here I can see that port 80 translates to 30990 & 443 to 30486. I've configured my external HAProxy load balancer to point to these ports it suggests they are up and running. I can also see HAProxy stats on port 1024:*31359*

I'm running a service called geoip - 

![statsscreen](https://user-images.githubusercontent.com/2487374/60805538-507c9480-a178-11e9-9746-929914d6228b.png)

My ingress rules look like this - 

````
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: geoip
spec:
  rules:
    - host: geoip.example.com
      http:
        paths:
          - backend:
              serviceName: geoip
              servicePort: 8080
````

Port 8080 is the port my image listens on and I can confirm this is working. I've also tested with nginx ingress with HAProxy as external LB and it works well.

However, when I try and access geoip.example.com via the external load balancer I just get an empty response. Any ideas why this would be?

Thanks,
Chris.
