### ISSUE TITLE
Question on whitelist

### ISSUE THREAD

**Issue by bsctl** [haproxytech/kubernetes-ingress#291]
## Question
We are using the `haproxy-ingress-controller` to expose a `sso server` (keycloak). Since we would expose publicly only the necessary OIDC urls, we're using an ingress with whitelist annotation enabled as per [doc](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#whitelist).

Public OIDC endpoints accessible from anywhere (no whitelisted)

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: infra
  labels:
  name: keycloak-access
  rules:
  - host: sso.example.com
    http:
      paths:
      - backend:
          service:
            name: keycloak-access
            port:
              number: 80
        path: /auth/realms/caas/protocol/openid-connect/auth
        pathType: ImplementationSpecific
      - backend:
          service:
            name: keycloak-access
            port:
              number: 80
        path: /auth/realms/caas/protocol/openid-connect/userinfo
        pathType: ImplementationSpecific
      - backend:
          service:
            name: keycloak-access
            port:
              number: 80
        path: /auth/realms/caas/protocol/openid-connect/token
        pathType: ImplementationSpecific
      - backend:
          service:
            name: keycloak-access
            port:
              number: 80
        path: /auth/realms/caas/protocol/openid-connect/logout
        pathType: ImplementationSpecific
      - backend:
          service:
            name: keycloak-access
            port:
              number: 80
        path: /auth/realms/caas/login-actions/authenticate
        pathType: ImplementationSpecific
      - backend:
          service:
            name: keycloak-access
            port:
              number: 80
        path: /auth/realms/caas/account
        pathType: ImplementationSpecific
      - backend:
          service:
            name: keycloak-access
            port:
              number: 80
        path: /auth/resources
        pathType: ImplementationSpecific
```

On the other side we want to keep private (whitelisted) all the other endpoints including the root url `/`

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    haproxy.org/whitelist: 10.0.0.0/8
    kubernetes.io/ingress.class: infra
  name: keycloak-exclude
spec:
  rules:
  - host: sso.example.com
    http:
      paths:
      - backend:
          service:
            name: keycloak-access
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
```

I assume a `first-match-win` logic so, for example, the `/auth/realms/caas/protocol/openid-connect/auth` is not whitelisted while `/`, `/auth`, and `/auth/realms` are.

However, with the above configurations I get denied (403 Forbidden - Request forbidden by administrative rules.) from public internet when trying to access `/auth/realms/caas/protocol/openid-connect/auth` while it works when in the whitelisted CIDR network. It looks the whitelisted ingress catches all. I'm missing something?

## Info
kubernetes v1.20
haproxy-ingress-controller v1.4.13 deployed with Helm Chart v1.9.0

 ```
kubectl -n ingress-system exec ingress-kubernetes-ingress-4stsd -- cat /etc/haproxy/haproxy.cfg | grep auth-system
  use_backend auth-system-keycloak-access-80 if { var(txn.host) sso.example.com } { var(txn.path) -m beg /auth/resources }
  use_backend auth-system-keycloak-access-80 if { var(txn.host) sso.example.com } { var(txn.path) -m beg /auth/realms/caas/protocol/openid-connect/userinfo }
  use_backend auth-system-keycloak-access-80 if { var(txn.host) sso.example.com } { var(txn.path) -m beg /auth/realms/caas/protocol/openid-connect/token }
  use_backend auth-system-keycloak-access-80 if { var(txn.host) sso.example.com } { var(txn.path) -m beg /auth/realms/caas/protocol/openid-connect/logout }
  use_backend auth-system-keycloak-access-80 if { var(txn.host) sso.example.com } { var(txn.path) -m beg /auth/realms/caas/protocol/openid-connect/auth }
  use_backend auth-system-keycloak-access-80 if { var(txn.host) sso.example.com } { var(txn.path) -m beg /auth/realms/caas/login-actions/authenticate }
  use_backend auth-system-keycloak-access-80 if { var(txn.host) sso.example.com } { var(txn.path) -m beg /auth/realms/caas/account }
  use_backend auth-system-keycloak-access-80 if { var(txn.host) sso.example.com } { var(txn.path) -m beg / }
  use_backend auth-system-keycloak-access-80 if { var(txn.host) sso.example.com} { var(txn.path) -m beg /auth/resources }
  use_backend auth-system-keycloak-access-80 if { var(txn.host) sso.example.com } { var(txn.path) -m beg /auth/realms/caas/protocol/openid-connect/userinfo }
  use_backend auth-system-keycloak-access-80 if { var(txn.host) sso.example.com } { var(txn.path) -m beg /auth/realms/caas/protocol/openid-connect/token }
  use_backend auth-system-keycloak-access-80 if { var(txn.host) sso.example.com } { var(txn.path) -m beg /auth/realms/caas/protocol/openid-connect/logout }
  use_backend auth-system-keycloak-access-80 if { var(txn.host) sso.example.com } { var(txn.path) -m beg /auth/realms/caas/protocol/openid-connect/auth }
  use_backend auth-system-keycloak-access-80 if { var(txn.host) sso.example.com} { var(txn.path) -m beg /auth/realms/caas/login-actions/authenticate }
  use_backend auth-system-keycloak-access-80 if { var(txn.host) sso.example.com } { var(txn.path) -m beg /auth/realms/caas/account }
  use_backend auth-system-keycloak-access-80 if { var(txn.host) sso.example.com } { var(txn.path) -m beg / }

```
