### ISSUE TITLE
No matching IngressClass haproxy.org/ingress.class: "haproxy"

### ISSUE THREAD

**Issue by alexcpn** [haproxytech/kubernetes-ingress#299]
I am getting the Error `No matching IngressClass haproxy.org/ingress.class: "haproxy"`. 

Without the annotation, it is working

![image](https://user-images.githubusercontent.com/1157251/113550817-546d6d00-9611-11eb-9cfb-13320741bf2c.png)

HAProxy Version

```
helm install kubernetes-ingress haproxytech/kubernetes-ingress --set controller.logging.level=debug --version 1.12.3
```

Ingress Annotation

```
HOST=nginx.10.X.X..8.112.nip.io
kubectl create -f - <<EOF
apiVersion: "networking.k8s.io/v1beta1"
kind: Ingress
metadata:
  name: nginx
  namespace: test-ingress
  annotations:
    haproxy.org/ingress.class: "haproxy"
     haproxy.org/rate-limit-period: "1m"
     haproxy.org/rate-limit-requests: "500"
spec:
  rules:
  - host: $HOST
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /
EOF
```

Kubernetes Version

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
