### ISSUE TITLE
Use proxy (v2) protocol per TCP service

### ISSUE THREAD

**Issue by bartversluijs** [haproxytech/kubernetes-ingress#302]
Hi,

I want to add the PROXY-V2 protocol to a TCP service, like so:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-vpn-tcp-services
data:
  443:
    default/vpn-service:443::PROXY-V2
```

However, this doesn't add the `send-proxy-v2` to the backend.  
I know about the annotation `send-proxy-protocol`, but this enabled the PROXY protocol for all backends. I just want to enable it for a specific TCP port.

Is this even possible at the moment?

Thanks in advance!
