### ISSUE TITLE
Follow also ingressClassName instead just annotation haproxy.org/ingress.class

### ISSUE THREAD

**Issue by radeno** [haproxytech/kubernetes-ingress#307]
Hello,

Do you plan to check Ingress Controller for Ingress `ingressClassName` definition?
If I understand it correctly, from Kubernetes v1.18 it is the preferred way how to define which ingress controller will be used.

Annotation `haproxy.org/ingress.class: haproxy` is straight, but it took me some time to understand why things don't work correctly when I defined only Spec `ingressClassName`

I think this can decrease the learning curve when somebody like me wants to implement Haproxy and has experience with default Kubernetes Nginx ingress.

Example:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: application
spec:
  ingressClassName: haproxy
```

Regards!

**Comment by Mo3m3n** [comment]
Hi,
Actually this is already implemented but the documentation was missing.
I have added it in the [doc section](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#ingressclass)
Thanks for reporting this.
However it is still required to define an `ingressClass` with controller value `haproxy.org/ingress-controller` which can look like:
```
---
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: haproxy
spec:
  controller: haproxy.org/ingress-controller
  ```
Maybe this something to automate with  [helm chart](https://github.com/haproxytech/helm-charts/tree/master/kubernetes-ingress)
