### ISSUE TITLE
HAProxy looking for secret for default namespace

### ISSUE THREAD

**Issue by brianrudolf-ep** [haproxytech/kubernetes-ingress#313]
I have HAProxy Kubernetes Ingress installed and am regularly seeing this warning message crop up. 
```
| kubernetes-ingress | 2021/05/05 13:30:20 WARNING haproxy/certificates.go:63 secret 'default/' does not exist
```

I don't set a `--namespace-whitelist`, which is my closest guess to something that may be related. I use a wildcard certificate for all my ingresses which is created by Cert-Manager and set in the HAProxy Helm chart values by :
```
  defaultTLSSecret:
    enabled: true
    secretNamespace: "${cert_namespace}"
    secret: "${cert_secret}"
```

Software | Version
--- | ---
HAProxy Helm Chart  | 1.14.2
HAProxy Ingress  | 1.6
AWS EKS | 1.18

Ingress definition:
[HAProxy-ingress.txt](https://github.com/haproxytech/kubernetes-ingress/files/6453355/HAProxy-ingress.txt)
Note I am transitioning from the community ingress controller to the haproxytech version, hence the seemingly duplicate annotations.
