### ISSUE TITLE
annotation haproxy.org/ssl-certificate ignored

### ISSUE THREAD

**Issue by alexkayzer** [haproxytech/kubernetes-ingress#326]
annotation haproxy.org/ssl-certificate ignored on harpoxy ingress via **Daemonset**.
Error:
**https/v4: SSL handshake failure**
ingress controller version:
**haproxytech/kubernetes-ingress:1.6.1**

config ingress:

```
apiVersion:  networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    haproxy.org/server-ssl: "true"
    haproxy.org/ssl-redirect: "false" 
    haproxy.org/server-proto: "h2"
    haproxy.org/ssl-certificate: "default/proxmox-secret"
    haproxy.org/ingress.class: "haproxy"
  name: proxmox-ingress
  namespace: default
spec:
  ingressClassName: "haproxy"
  rules:
  - host: proxmox.romanovs.ml
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: proxmox-ext
            port:
              number: 8006
```
if add block:
```
                tls:
                - hosts:
                  - proxmox.romanovs.ml
                  secretName: proxmox-secret
```
it works.
