### ISSUE TITLE
Ingress with ssl-passthrough redirects all traffic

### ISSUE THREAD

**Issue by eandre** [haproxytech/kubernetes-ingress#340]
I'm seeing behavior where the ingress controller forwards *all* traffic (including the health check and haproxy-stats endpoints on ports 1042 and 1024) whenever I define an ingress with `ssl-passthrough: "true"`. See below for configuration.

## Ingress
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    haproxy.org/ssl-passthrough: "true"
  name: foo-gateway
  namespace: some-namespace
spec:
  rules:
  - host: "foo.gateway"
    http:
      paths:
      - backend:
          service:
            name: gateway
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - "foo.gateway"
```

## Ingress Controller
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-controller
  namespace: external-ingress
spec:
  template:
    spec:
      containers:
      - args:
        - --configmap=external-ingress/external-ingress-controller
        - --ingress.class=haproxy
        - --log=debug
        - --default-backend-service=external-ingress/external-ingress-default-backend
        env:
        - name: TZ
          value: Etc/UTC
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: haproxytech/kubernetes-ingress:1.6.2
        imagePullPolicy: IfNotPresent
        name: controller
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 1024
          name: stat
          protocol: TCP
        - containerPort: 1042
          name: health
          protocol: TCP
        resources:
          requests:
            cpu: 500m
            memory: 50Mi
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          runAsGroup: 1000
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - /bin/sh
        - -c
        - sysctl -w net.ipv4.ip_unprivileged_port_start=0
        image: busybox:musl
        imagePullPolicy: IfNotPresent
        name: sysctl
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: external-ingress
      serviceAccountName: external-ingress
      terminationGracePeriodSeconds: 30
```

When I run `kubectl -n external-ingress port-forward $CONTROLLER_POD 1042:1042` I can normally access the health check:

```bash
$ curl http://localhost:1042/healthz
<html><body><h1>200 OK</h1>
Service ready.
</body></html>
```

But as soon as I define the ingress, I get:

```bash
$ curl localhost:1042/healthz
curl: (52) Empty reply from server
```

And the port forwarding logs state:
```bash
$ kubectl -n external-ingress port-forward $CONTROLLER_POD 1042:1042
Forwarding from 127.0.0.1:1042 -> 1042
Forwarding from [::1]:1042 -> 1042
Handling connection for 1042
E0608 16:59:58.470240   34139 portforward.go:400] an error occurred forwarding 1042 -> 1042: error forwarding port 1042 to pod d088c3365fe53d91c0917de46c4610b6a6ae28f96f60f2943567c69ceb0799cc, uid : exit status 1: 2021/06/08 14:59:58 socat[6301] E connect(5, AF=2 127.0.0.1:1042, 16): Connection refused
E0609 01:15:28.371810   34139 portforward.go:233] lost connection to pod
```

Am I missing something obvious?
