### ISSUE TITLE
make ssl-redirect available at the ingress or service level

### ISSUE THREAD

**Issue by bedis** [haproxytech/kubernetes-ingress#35]
current implementation of ssl-redirect is make "globally", for all the traffic.
That said, we may want to enable this per ingress rule or per kubernetes service only.

**Comment by ejez** [comment]
Strongly agree...
An example use is let's encrypt cert generation, we don't want to redirect for path "/.well-known/"
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-app
  annotations:
    haproxy.org/ssl-redirect: "OFF"
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /.well-known/
        backend:
          serviceName: my-backend
          servicePort: 80
```
