### ISSUE TITLE
How do I get a single Ingress to be handled by just one of two HAProxy Ingress Controllers  on AKS?

### ISSUE THREAD

**Issue by cdhunt** [haproxytech/kubernetes-ingress#354]
Full Question: https://stackoverflow.com/questions/68580249/how-do-i-get-two-haproxy-ingress-controllers-to-handling-a-single-ingress-on-aks

tl;dr. I have two ingress controllers. I'm using `ingressClassName` to associate `Ingress` resources with one or the other. However, I only have one Ingress set up configured with one `ingressClassName` but both controllers are servicing requests.

**Comment by bluebrown** [comment]
have you tried giving the second one a proper class instead of `--empty-ingress-class`?. 

As far as I understand, with this flag it will handle all ingress resources with and without class-name. I think its meant to use when you have only 1 controller that should handle everything and don't want to add that class everywhere. 

But the way you try it would also make sense and be good IMO. Maybe there should be a third flag, `handle-all-ingress` or something.

**Comment by cdhunt** [comment]
Yeah, the internal Ingress has a class and the empty class argument. The external just has the class argument and it still seems to handle all requests regardless of class.

**Comment by Mo3m3n** [comment]
Hi  @cdhunt 
When I run Ingress Controller with `--ingress.class` set to "internal-lb` it only deals with Ingress resources having `kubernetes.io/ingress.class: internal-lb` so it works as expected and I can't reproduce your issue.
Can you provide the following:
- Ingress Controller version
- Ingress Controller params (command line args) for both controllers

**Comment by cdhunt** [comment]
Thanks for the follow-up. I'm out this week. I'll post those details next week.

**Comment by cdhunt** [comment]
External

```yaml
           ...
          image: haproxytech/kubernetes-ingress:1.6.5
          args:
            - --configmap=ext-haproxy-controller/haproxy
            - --default-backend-service=ext-haproxy-controller/ingress-default-backend
            - --disable-ipv6
            - --ingress.class=external-lb
            ...
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: external-lb
spec:
  controller: haproxy.org/ingress-controller
  parameters:
    apiGroup: k8s.example.com
    kind: IngressParameters
    name: hapxroxy-ext
```

Internal

```yaml
          ...
          image: haproxytech/kubernetes-ingress:1.6.5
          args:
            - --configmap=haproxy-controller/haproxy
            - --default-backend-service=haproxy-controller/ingress-default-backend
            - --disable-ipv6
            - --ingress.class=internal-lb
            - --empty-ingress-class
            ...
---
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: internal-lb
  annotations:
    "ingressclass.kubernetes.io/is-default-class": "true"
spec:
  controller: haproxy.org/ingress-controller
  parameters:
    apiGroup: k8s.example.com
    kind: IngressParameters
    name: internal-lb
```

Ingress

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    "kubernetes.io/ingress.class": internal-lb
spec:
  ingressClassName: internal-lb
  rules:
  - host:  oursite.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: site
            port:
              number: 80
```

**Comment by cdhunt** [comment]
Also confirmed that both controllers have the same backends configured.

**Comment by sniip-code** [comment]
@cdhunt I think the issue is this class func igClassIsSupported() [](https://github.com/haproxytech/kubernetes-ingress/blob/d103eeeefbb8fb8d217c5e193d85656cb35e09e4/controller/ingress.go#L32)

If IngressClassName is set it matches on all controllers as they are all "haproxy.org/ingress-controller". 

I fixed it by removing  "ingressClassName" annotation. The legacy code works only matching on controllers with matching ingress.class.

So just remove ingressClassName and leave "kubernetes.io/ingress.class" set with your className matching the className in the haproxy startup args.  

I also found it useful to port forward to the stats web interface and see what backend services have been mapped. Before i removed IngressClassName I had services backends from other ingress files.

kubectl port-forward "nameOfIngressPod" 1024

The go to: http://127.0.0.1:1024

Before and after removing "IngressClassName" check the web interface only has backend services for the services in the ingress.  When I had "ingressClassName" annotation set there were backend services from other ingress files, when i removed it only had the correct backend services.

Tell me how you go..

Cheers,

**Internal**
`
          image: haproxytech/kubernetes-ingress:1.6.5
          args:
            - --configmap=ext-haproxy-controller/haproxy
            - --default-backend-service=ext-haproxy-controller/ingress-default-backend
            - --disable-ipv6
            - --ingress.class=external-lb
            ...
`
`
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    "kubernetes.io/ingress.class": internal-lb
spec:
  rules:
  - host:  oursite.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: site
            port:
              number: 80
`


**External**
`
          image: haproxytech/kubernetes-ingress:1.6.5
          args:
            - --configmap=ext-haproxy-controller/haproxy
            - --default-backend-service=ext-haproxy-controller/ingress-default-backend
            - --disable-ipv6
            - --ingress.class=external-lb
            ...
`

`
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    "kubernetes.io/ingress.class": external-lb
spec:
  rules:
  - host:  other.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: site
            port:
              number: 80
`

**Comment by cdhunt** [comment]
@sniip-code That was it and I think the only combination I didn't try. Thank you!

To summarize, `ingressClassName` with `IngressClass` doesn't work when you have multiple haproxy controllers. I assume it works fine when the controllers are different controller types.

**Comment by cdhunt** [comment]
@sniip-code Do you want to add an answer to https://stackoverflow.com/questions/68580249/how-do-i-get-a-single-ingress-to-be-handled-by-just-one-of-two-haproxy-ingress-c?

**Comment by Mo3m3n** [comment]
Thanks @sniip-code for taking the time to look into this issue !
@cdhunt on my first post I have missed the `ingressClassName` test so I was not able to replicate this before reading @sniip-code message
To make things clearer there are two different methods to assign Ingress resources to Ingress Controllers.
- `IngressClass` Kind: relying on `IngressClass` resource and `IngressClassName` field)
- `ingress.class` annotation: relying on the controller argument `--ingress.class`

The first one is the [officially](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class) supported method and the second one is the [legacy one](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation).
We support both of them, but here we have a buggy behavior with `IngressClassName` that needs to be fixed.

> To summarize, ingressClassName with IngressClass doesn't work when you have multiple haproxy controllers. I assume it works fine when the controllers are different controller types.

To be more accurate the issue here is only with `ingressClassName`, our Ingress Controller is not currently processing the `params` field in the IngressClass but only the `controller` field. So if the `controller` field is matching,  the ingress resource will be processed, which means all haproxy controllers will be involved without being able to differentiate them.
That's why when you remove `ingressClassName` the issue disappears and `ingress.class` is doing the job correctly .
```
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: external-lb
spec:
  controller: haproxy.org/ingress-controller
  parameters:
    apiGroup: k8s.example.com
    kind: IngressParameters
    name: external-lb
```


I am currently working on providing a fix for this. Will keep you posted here as soon as it is pushed and released.

**Comment by sniip-code** [comment]
> @sniip-code Do you want to add an answer to https://stackoverflow.com/questions/68580249/how-do-i-get-a-single-ingress-to-be-handled-by-just-one-of-two-haproxy-ingress-c?

I replied to your stackoverflowq question.

**Comment by Mo3m3n** [comment]
This was fixed in `haproxytech/kubernetes-ingress:1.7.1` and a dedicated [documentation section](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/ingressclass.md) is available.

**Comment by hziegeldorf** [comment]
@Mo3m3n, latest Helm chart `1.17.5` uses `haproxytech/kubernetes-ingress:1.7.1` and sets `--ingress.class=haproxy` per default.

```
$: helm3 template haproxy haproxytech/kubernetes-ingress
...
      containers:
        - name: kubernetes-ingress-controller
          image: "haproxytech/kubernetes-ingress:1.7.1"
          imagePullPolicy: IfNotPresent
          args:
          - --default-ssl-certificate=test/haproxy-kubernetes-ingress-default-cert
          - --configmap=test/haproxy-kubernetes-ingress
          - --default-backend-service=aedifion-io/haproxy-kubernetes-ingress-default-backend
          - --ingress.class=haproxy
          - --publish-service=test/haproxy-kubernetes-ingress
          - --log=info
 ```

Is this on purpose? Going by the [documentation](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/ingressclass.md#ingressclass-annotation), this means that even in the case of a single Ingress controller I'd have to set my IngressClass like this, which seems a bit awkward:

```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: haproxy-haproxy
spec:
  controller: haproxy.org/ingress-controller/haproxy
```
