### ISSUE TITLE
make namespace and service name and portname available as variable in config and annotations

### ISSUE THREAD

**Issue by nbraun-wolf** [haproxytech/kubernetes-ingress#364]
Hi, as I am setting up linkerd with the haproxy controller, I thought it would be great if the namespace service name  and portname could be accessed in config snippets and annotations.

AS example from the[ nginx controller integration documentation](https://linkerd.io/2.10/tasks/using-ingress/#nginx):

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-headers
  namespace: ingress-nginx
data:
  proxy_set_header: "l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;"
```

After experimenting for some time I managed to get those three things in the header but unfortunately thei are joined with a hpyhen.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy
  namespace: ingress
data:
 backend-config-snippet: |
    http-request set-header X-Test %b 
```

So the result looks something like this: `X-Test: demo-app-port-1`. This is already pretty close but not good enough. Because its virtually impossible to try to split this on the hyphens unless we would contrain ourself to not use hyphens in any resource names.

After digging for some time in the codebase, I found out that this `%b` (backend) is set via `%[var(txn.path_match),field(1,.)]`. 

I think 2 options could make sense. 

1. Introduce 3 new variables that contain only the names of namespace, servicename, and portname. Something like `%ns`, `%sn` and `%pn`.
2. Allow to set the delimiter ourselves so that we can use `field` to split those names. i.e. using the tilde `demo~app~port-1`. and then do something like.
```
http-request set-header X-Test %[var(txn.path_match),field(2,-)].%[var(txn.path_match),field(1,-)].cluster.local:%[var(txn.path_match),field(3,-)]
```
