### ISSUE TITLE
Returning 503s when the api server is down

### ISSUE THREAD

**Issue by benjamin-bergia** [haproxytech/kubernetes-ingress#377]
I recently had some issues with the master of one of our clusters and I noticed that when the API server went down, HAProxy started to return 503 almost immediately on all my ingresses.

From the doc it seems like HAProxy is only running TCP and HTTP checks directly on the endpoints to check their health. Do you have any idea why the availability of the API might have an impact on the availability of my ingresses. Is there any way to prevent this kind of situation?

**Comment by ivanmatmati** [comment]
Hi @benjamin-bergia , I've run a local test with api server down and I still managed to reach the destination through haproxy managed by controller. Could you describe the conditions ? What type of  k8s cluster, what controller version you used, the ingress configuration for the failing requests, from where the requests were sent, etc. Thanks.

**Comment by benjamin-bergia** [comment]
Hi @imatmati , 

thank you for you reply. We are running kubernetes v1.21 with 5 masters. The controller is in version 1.5.3.  Our cloud provider runs a loadbalancer in front of the master to provide a single IP for the API. We had an incident where the loadbalancer in front of the 5 masters went down so none of the nodes could connect to the API on any of the masters.

I use the following manifest: https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.5.3/deploy/haproxy-ingress-daemonset.yaml

And here are my modifications to it (via kustomize):
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.5.3/deploy/haproxy-ingress-daemonset.yaml

namespace: haproxy-controller

commonLabels:
  app.kubernetes.io/name: haproxy

patches:
  - target:
      kind: DaemonSet
      name: haproxy-ingress
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          role: ingress
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - '--configmap=haproxy-controller/haproxy-configmap'
          - '--default-backend-service=haproxy-controller/ingress-default-backend'
  - target:
      kind: ConfigMap
      name: haproxy-configmap
    patch: |-
      - op: add
        path: /data
        value:
          syslog-server: "address:stdout, format: raw, facility:daemon"
          timeout-client: '30s'
          timeout-connect: '30s'
          timeout-server: '5m'
  - target:
      kind: Service
      name: haproxy-ingress
    patch: |-
      - op: replace
        path: /spec/ports/2/name
        value: metrics

images:
  - name: haproxytech/kubernetes-ingress
    newTag: 1.5.3
```
