### ISSUE TITLE
Annotation "server-ca" doesn't work in service resource

### ISSUE THREAD

**Issue by davidledev** [haproxytech/kubernetes-ingress#409]
Hello, I use the 1.17.11 chart version (and so image haproxytech/kubernetes-ingress:1.7.3). When I try to set up `server-ca` annotation backend side (https://www.haproxy.com/documentation/kubernetes/latest/configuration/service/#server-ca), I obtain the following error in controller log:
```
msg="Proxy 'ha-proxy-tech-test-svc-443', server 'SRV_1' [/etc/haproxy/haproxy.cfg.baa1e759-d0a8-4d7e-a409-e065ec8f4ebc:143] verify is enabled by default but no CA file specified. If you're running on a LAN where you're certain to trust the server's certificate, please set an explicit 'verify none' statement on the 'server' line, or use 'ssl-server-verify none' in the global section to disable server-side verifications by default."
msg="Fatal errors found in configuration." msg="Fatal errors found in configuration
````
Here my configuration:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-haproxytech
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  rules:
  - host: xxxx.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-svc
            port:
              number: 443
---
apiVersion: v1
kind: Service
metadata:
  name: test-svc
  annotations:
    haproxy.org/check: "false"
    haproxy.org/server-ca: "ns/server-root-ca"
spec:
  externalName: xxxx.example2.com
  type: ExternalName
  ports:
  - port: 443
```
However, I see the ca file in path "/etc/haproxy/certs/ca".
Then i change the service with `backend-config-snippet` and the request works.
```
apiVersion: v1
kind: Service
metadata:
  name: test-svc
  annotations:
    haproxy.org/check: "false"
    haproxy.org/backend-config-snippet: |
      server test xxx.example2.com:443 ssl verify required ca-file /etc/haproxy/certs/ca/ns_server-root-ca.pem sni str(xxx.example2.com)
spec:
  externalName: xxx.example2.com
  type: ExternalName
  ports:
  - port: 443
```
