### ISSUE TITLE
Using basic auth prevents ACME challenge from completing

### ISSUE THREAD

**Issue by ohemelaar** [haproxytech/kubernetes-ingress#437]
Hi,

I've had an issue where a certificate challenge wouldn't complete due to an error: `wrong status code '401', expected '200'`.

Disabling basic auth manually on the ingress allowed the challenge to complete. However, I can see this process getting cumbersome when handling many ingresses. Shouldn't the ingress allow the challenge to complete even though it uses basic auth?

Annotations used:
```yaml
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    haproxy.org/auth-secret: basic-app-auth
    haproxy.org/auth-type: basic-auth
    kubernetes.io/ingress.class: haproxy
```
