### ISSUE TITLE
haproxy-ingress-controller just serves the default-ssl-certificate set on the yaml

### ISSUE THREAD

**Issue by gschanuel** [haproxytech/kubernetes-ingress#44]
When using haproxy-ingress-controller, it just serves the default-ssl-certificate set on the yaml.

I have verified the secret which contains the needed certificate (generated by cert-manager) and it is correct.

This secret is not linked anywhere. There is no other cert file in /etc/haproxy/certs than the one specified in default-ssl-certificate.

The certificate is set on the ingress session from my chart like below

```
 ssl-certificate: lool/sub-server-tls
    hosts:
    - sub.mydomain.com
  tls:
    - secretName: lool-server-tls
      hosts:
        - sub.mydomain.com
```

I had made a few changes on haproxy-ingress.yaml to adjust to my needs and system. Even if I don't see how these changes could interfere on the ssl part, see the attachment.
[haproxy-ingress.yaml.txt](https://github.com/haproxytech/kubernetes-ingress/files/3433202/haproxy-ingress.yaml.txt)
This is the haproxy.cfg from inside the pod
[haproxy.cfg.txt](https://github.com/haproxytech/kubernetes-ingress/files/3433298/haproxy.cfg.txt)

**Comment by oktalz** [comment]
Hi @gschanuel,

you can expect fix for this in next few days.
I'll notify you when this will be ready

**Comment by oktalz** [comment]
new version v1.2.0 is released that fixes the behavior.
please note that if you define secret in ingress object, 
you do not need to define default certificate in order to use https

**Comment by oktalz** [comment]
format that controller expects is something like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: app
 namespace: default
 annotations:
   ingress.class: haproxy
spec:
 tls:
  - hosts:
	- foo.bar
	secretName: default/tls-secret
 rules:
 - host: foo.bar
   http:
	 paths:
              ......
```
regarding secret format, it is same as for default secret
https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#tls-secret
