### ISSUE TITLE
Annotation request-set-header "X-Forwarded-Proto" does not work

### ISSUE THREAD

**Issue by Overbryd** [haproxytech/kubernetes-ingress#441]
Hi,

I have an haproxy ingress controller setup, with the following ingress:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    haproxy.org/forwarded-for: "true"
    haproxy.org/request-set-header: X-Forwarded-Proto https
    kubernetes.io/ingress.class: haproxy
  name: httpbin
  namespace: httpbin
spec:
  rules:
  - host: httpbin.foo.de
    http:
      paths:
      - backend:
          service:
            name: httpbin-web
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - httpbin.foo.de
    secretName: wildcard-foo-de
status:
  loadBalancer: {}
```

Requests are being forwarded, SSL works and all, but the backend service does not receive the "X-Forwarded-Proto" header which is so dearly required.

What is wrong? I could not find anything in the documentation that this header won't be set.
