### ISSUE TITLE
Foreign IP in haproxy.cfg.

### ISSUE THREAD

**Issue by rickyticky2** [haproxytech/kubernetes-ingress#445]
Hello . can anyone have ideas .. installed ingress controller haproxy. shared via nodeport , made a configmap for tcp with a port for the service. The service has one endpoint, and haproxy.cfg takes two ip from somewhere. and the connection works every other time .... in the logs it is clear that this ip is not connected

[WARNING] (259) : Server uat-mqtt-gateway-mqtt/SRV_1 is DOWN, reason: Layer4 timeout, check duration: 2000ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.

[WARNING] (259) : Server uat-mqtt-gateway-mqtt-tls/SRV_1 is DOWN, reason: Layer4 connection problem, info: "Host is unreachable", check duration: 1890ms. 1 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.

 
```
apiVersion: v1
data:
  "1883": uat/mqtt-gateway:1883
  "8883": uat/mqtt-gateway:8883
kind: ConfigMap
metadata:
  creationTimestamp: "2022-05-20T13:26:44Z"
  name: tcp-services
  namespace: ingress-haproxy
  resourceVersion: "71032679"
  uid: f16c0389-c6d4-4bd1-9ec0-e2fdc7cef979 
```
added to deployment  - `--tcp-services-configmap=ingress-haproxy/tcp-services`

svc:

 ```
spec:
  clusterIP: 10.98.142.212
  clusterIPs:
  - 10.98.142.212
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30341
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 31856
    port: 443
    protocol: TCP
    targetPort: https
  - name: stat
    nodePort: 32563
    port: 1024
    protocol: TCP
    targetPort: stat
  - name: mqtt
    nodePort: 32127
    port: 1883
    protocol: TCP
    targetPort: 1883
  - name: mqtts
    nodePort: 31944
    port: 8883
    protocol: TCP
    targetPort: 8883
  selector:
    app.kubernetes.io/instance: haproxy-ingress
    app.kubernetes.io/name: kubernetes-ingress
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```
![capture_20220523155508806](https://user-images.githubusercontent.com/79316032/169818953-54059cdb-41e5-4dc0-842b-c1ff720ef03e.jpg)
![capture_20220523154542119](https://user-images.githubusercontent.com/79316032/169818957-79c5748f-0878-4079-aca8-4a35ad57b005.jpg)
![capture_20220523154703848](https://user-images.githubusercontent.com/79316032/169818959-b93aa345-8e9c-4b2e-b1ba-4bd65c0e64f2.jpg)
