### ISSUE TITLE
Backend Servers not created/updated since v.1.7.11

### ISSUE THREAD

**Issue by dschuldt** [haproxytech/kubernetes-ingress#460]
Hi,

since the 1.7.11 update (happens with 1.8.0 as well) we experience the following issue (K8s version 1.22):

If an ingress is configured with a path type exact rule, the resulting backend is started without servers. 

Example:

```
- path: /actuator/health/readiness
  pathType: Exact
  backend:
    service:
      name: api-gateway-master
      port:
        name: management
```

![Screenshot 2022-06-14 112240](https://user-images.githubusercontent.com/15954969/173544716-935db069-17f8-49ca-b568-ebac31f3de4c.png)

With version 1.7.10 (server slots scaled to "5"):

![Screenshot 2022-06-14 112343](https://user-images.githubusercontent.com/15954969/173544872-0e8db9af-f5d7-4f24-b774-c99da06bdb18.png)

After some time/ some reloads of services and ingress controller, the servers are applied. I cannot tell which action actually helps. But if we update the ingress or service resource, e.g. rename a port, the change is not updated to haproxy config, although the log clearly says an update is necessary and performed.

This is the spec of the corresponding service:

````
...
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: management
    port: 9443
    protocol: TCP
    targetPort: management
  selector:
    app: api-gateway
    branch: master
```

If I can assist with this issue please let me know. 

Thanks a lot!

Best
Denis

**Comment by fabianonunes** [comment]
Hi, @dschuldt.

I could not reproduce the bug. I debugged the code involved in creating backends and could find no apparent flaws.

Can you post the `values.yaml` and the other annotations of the problematic Service?

**Comment by dschuldt** [comment]
Hi @fabianonunes,

we do not deploy the controller with helm but with the plain manifests in the repo.

The controller runs with the following args:

```
args:
  - --configmap=haproxy-controller/haproxy-kubernetes-ingress
  - --default-backend-service=haproxy-controller/haproxy-kubernetes-ingress-default-backend
  - --configmap-tcp-services=haproxy-controller/tcpservices
  - --default-ssl-certificate=haproxy-controller/wildcard-cert
  - --publish-service=haproxy-controller/haproxy-kubernetes-ingress-lb
  - --disable-ipv6
```

The configmap spec:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-kubernetes-ingress
  namespace: haproxy-controller
data:
  syslog-server: "address:stdout, format: raw, facility:daemon"
  forwarded-for: "false"
  request-capture: |
    hdr(Host)
    hdr(X-Forwarded-For)
  timeout-client: 60s
  timeout-server: 60s
  frontend-config-snippet: |
    option forwardfor if-none
  stats-config-snippet: |
    http-request set-log-level silent
  scale-server-slots: "5"
```

The full service spec (manifest templated with ansible before deployment):

```
---
apiVersion: v1
kind: Service
metadata:
  name: {{ extra_vars_service_name }}
  namespace: {{ extra_vars_namespace }}
  labels:
    app: {{ extra_vars_app_name }}
    version: "{{ extra_vars_tag }}"
    springBootAdmin: enabled
spec:
  selector:
    app: {{ extra_vars_app_name }}
    branch: "{{ extra_vars_branch }}"
  ports:
    - name: https
      port: 443
      targetPort: https
    - name: management
      port: 9443
      targetPort: management
```

The full Ingress spec:

```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ extra_vars_deployment_name }}
  namespace: {{ extra_vars_namespace }}
  labels:
    app_name: {{ extra_vars_app_name }}
    version: "{{ extra_vars_tag }}"
  annotations:
    haproxy.com/server-ssl: "true"
spec:
  tls:
  - hosts:
      - {{ extra_vars_host_url }}
    secretName: wildcard-cert
  rules:
  - host: {{ extra_vars_host_url }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ extra_vars_service_name }}
            port:
              name: https
      - path: /actuator/health/readiness
        pathType: Exact
        backend:
          service:
            name: {{ extra_vars_service_name }}
            port:
              name: management
```


Thanks for your help.
