### ISSUE TITLE
NLB Target groups health checks are failing when proxy-protocol is enabled

### ISSUE THREAD

**Issue by apanagiotou** [haproxytech/kubernetes-ingress#463]
I've been trying to expose a TCP service in Kubernetes through HAProxy ingress controller and I want to filter traffic based on the source IP addresses. The HAproxy controller is fronted by an AWS NLB so I enabled proxy protocol on the NLB target group for this tcp service but the moment I did it, I saw all targets on the NLB reported as unhealthy. Let me explain..

The haproxy controller service
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "600"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "false"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: haproxy
  namespace: ingress
spec:
  externalTrafficPolicy: Local
  healthCheckNodePort: 30029
  ports:
  - name: sftp-test-tcp
    port: 55922
    protocol: TCP
    targetPort: 55922
  selector:
    app.kubernetes.io/instance: haproxy
    app.kubernetes.io/name: kubernetes-ingress
  type: LoadBalancer
```

creates the NLB successfully, the target group for the TCP service and the health check works for this target group (5 healthy targets). I.e.:
```
Protocol
HTTP

Path
/healthz

Port
30029

Healthy threshold
2 consecutive health check successes

Unhealthy threshold
2 consecutive health check failures

Timeout
6 seconds

Interval
10 seconds

Success codes
200-399
```

But when I enable the proxy-protocol on the target group, all healthy targets become unhealthy. This is due to the fact that when you enable the proxy protocol on the NLB, it forces proxy protocol headers in the health check requests as well. But the HAproxy healthz frontend is not configured to accept proxy protocol:
```
frontend healthz
  mode http
  bind 0.0.0.0:1042 name v4
  bind :::1042 name v6 v4v6
  monitor-uri /healthz
  option dontlog-normal
```

I suppose the solution is to add _accept-proxy_ on the bind attribute but I don't find a way to do it. I've searched all configuration options on HAproxy and the helm chart repos but I can't find anything. By the way, I have calico as the CNI on my cluster (I'm not sure if it's that that doesn't understand proxy-protocol and doesn't even forward the request to haproxy).

Versions:
Kubernetes: 1.20
HAProxy version: 2.4.15-7782e23

Any ideas? Thanks in advance
