### ISSUE TITLE
ssl-redirect not working when ssl-passthrough is enabled

### ISSUE THREAD

**Issue by yerkanian** [haproxytech/kubernetes-ingress#466]
**Description of the problem**

I’m trying to set up ssl-passthrough to container’s port 443 with ssl-redirect on port 80, but no matter what I try haproxy-ingress gives 404 on port 80.

**Expected behavior**

haproxy-ingress should generate a redirect for requests arriving on port 80 to the service port 443.

Configuration to reproduce the problem:

```
---
apiVersion: v1
kind: Service
metadata:
  namespace: test
  labels:
    run: echoapp
  name: echoapp      
  annotations:
    haproxy.org/check: "true"
    haproxy.org/forwarded-for: "true"   
    haproxy.org/load-balance: "roundrobin"
spec:
  selector:
    run: echoapp
  ports:  
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443

--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  namespace: test   
  annotations:
    haproxy.org/ssl-redirect: "true"
    haproxy.org/ssl-redirect-code: "301"
    haproxy.org/ssl-passthrough: "true" 
spec:
  tls:
  - hosts:
    - test.local
  rules:
  - host: test.local
    http:
      paths:
      - path: /  
        pathType: Prefix
        backend:
          service:
            name: echoapp
            port:
              number: 443
```

curl example:
```
% curl -v http://test.local/
*   Trying 192.168.0.165:80...
* Connected to test.local (192.168.0.165) port 80 (#0)
> GET /HTTP/1.1
> Host: test.local
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< date: Fri, 24 Jun 2022 10:41:09 GMT
< content-type: text/plain; charset=utf-8
< content-length: 9
< 
* Connection #0 to host test.local left intact
Not Found
```
