### ISSUE TITLE
SSL protocol error after controller upgrade

### ISSUE THREAD

**Issue by dfateyev** [haproxytech/kubernetes-ingress#467]
I have upgraded HAProxy controller from an earlier to the latest version (1.8.3).
Unfortunately, an ingress resource for SSL-based backend (actually, the Kubernetes dashboard) stopped working.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
  annotations:
    haproxy.org/path-rewrite: /kubernetes-dashboard(/|$)(.*) /\2
    haproxy.org/server-ssl: 'true'
    haproxy.org/check: 'false'
spec:
  ingressClassName: haproxy
  rules:
  - http:
      paths:
      - path: /kubernetes-dashboard
        pathType: Prefix
        backend:
          service:
            name: kubernetes-dashboard
            port:
              number: 443
```
Now, I have `"502 Bad Gateway"` error in HAProxy frontend, and in dashboard logs:
```
2022/07/21 09:25:51 http2: server connection error from 10.239.96.1:49972: connection error: PROTOCOL_ERROR
2022/07/21 09:25:52 http2: server connection error from 10.239.128.2:51292: connection error: PROTOCOL_ERROR
```
What can be wrong in this configuration? It worked fine at least for 1.6.x controller versions.

If I remove the `"server-ssl"` annotation, I get `"Client sent an HTTP request to an HTTPS server"` valid error as expected.
