### ISSUE TITLE
Loadbalancing algorithm is not working for tcp mode backends

### ISSUE THREAD

**Issue by benm-stm** [haproxytech/kubernetes-ingress#479]
I use the below helm  chart to install haproxy ingress 
`helm install --namespace ingress-controller --create-namespace --set controller.ingressClass='haproxy-pub',controller.ingressClassResource.name='haproxy-pub',controller.kind='DaemonSet',controller.extraArgs={'--configmap-tcp-services=solacescalable/solacescalable-pub-tcp-ingress'} haproxy-pub haproxytech/kubernetes-ingress`
```
apiVersion: v1
data:
  "1883": solacescalable/default-default-1883-pub:1883
  "5671": solacescalable/default-default-5671-pub:5671
  "5672": solacescalable/default-default-5672-pub:5672
  "8000": solacescalable/default-default-8000-pub:8000
  "8443": solacescalable/default-default-8443-pub:8443
  "8883": solacescalable/default-default-8883-pub:8883
  "9000": solacescalable/default-default-9000-pub:9000
  "9443": solacescalable/default-default-9443-pub:9443
kind: ConfigMap
metadata:
  labels:
    app: solacescalable
  name: solacescalable-pub-tcp-ingress
  namespace: solacescalable
```

i changed  the already created configmap to change the loadbalancing to leastconn  like below
```
apiVersion: v1
data:
  load-balance: leastconn
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: haproxy-pub
    meta.helm.sh/release-namespace: ingress-controller
  creationTimestamp: "2022-08-21T16:22:32Z"
  labels:
    app.kubernetes.io/instance: haproxy-pub
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-ingress
    app.kubernetes.io/version: 1.8.3
    helm.sh/chart: kubernetes-ingress-1.22.4
  name: haproxy-pub-kubernetes-ingress
  namespace: ingress-controller
```
when i check the haproxy.cfg in the daemonset pod, i find that the loadbalancing is applied to http mode backend but not tcp mode
```
$kubectl exec -ti -n ingress-controller haproxy-pub-kubernetes-ingress-bwqbx -- cat /etc/haproxy/haproxy.cfg | grep -B2  balance

backend ingress-controller_haproxy-pub-kubernetes-ingress-default-backend_http
  mode http
  balance leastconn
--
  backend solacescalable_default-default-1883-pub_1883
  mode tcp
  balance roundrobin
--
  backend solacescalable_default-default-5671-pub_5671
  mode tcp
  balance roundrobin
--
  backend solacescalable_default-default-5672-pub_5672
  mode tcp
  balance roundrobin
--
  backend solacescalable_default-default-8000-pub_8000
  mode tcp
  balance roundrobin
--
  backend solacescalable_default-default-8443-pub_8443
  mode tcp
  balance roundrobin
--
  backend solacescalable_default-default-8883-pub_8883
  mode tcp
  balance roundrobin
--
  backend solacescalable_default-default-9000-pub_9000
  mode tcp
  balance roundrobin
--
  backend solacescalable_default-default-9443-pub_9443
  mode tcp
  balance roundrobin
--
  backend solacescalable_solacescalable-0_8080
  mode http
  balance leastconn
--
  backend solacescalable_solacescalable-1_8080
  mode http
  balance leastconn
--
  backend solacescalable_solacescalable-2_8080
  mode http
  balance leastconn
```
I'm i using the right configmap key or is TCP not supported yet ?
