### ISSUE TITLE
Basic-auth doesn't work 

### ISSUE THREAD

**Issue by AlexisDuf** [haproxytech/kubernetes-ingress#48]
Hi, 

I deployed the haproxy ingress controller and everything seems to work fine except the basic-auth. 

For one of my Ingress I need to set basic-auth. My ingress file looks like this: 
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/auth-realm: Authentication Required
    ingress.kubernetes.io/auth-secret: basic-auth
    ingress.kubernetes.io/auth-type: basic
  name: prometheus
  namespace: monitoring
spec:
  rules:
  - host: prometheus.example.fr
    http:
      paths:
      - backend:
          serviceName: prometheus-k8s
          servicePort: web
```

And when I access to my prometheus dashboard I don't need to set my password. It doesn't seems to consider my annotations

Did I miss something or it's not possible to set basic auth with haproxy ingress controller?

**Comment by bedis** [comment]
Hi,

This kubernetes ingress controller does not support yet basic authentication. Plus, as far as I can see, you also miss some "login/password" into your annotations, to make a full configuration.

Mind if I turn your issue as a feature request?

**Comment by AlexisDuf** [comment]
Hi @bedis 

login/password are stored in secret config called `basic-auth` 
Yes you can turn it as a feature ;) would be nice to have it :) 

Thanks

**Comment by bedis** [comment]
Ok understood.
Thx for your feedback.

**Comment by rossbeazley** [comment]
any hints on a roadmap time for this?

**Comment by Mo3m3n** [comment]
Hey @AlexisDuf  @rossbeazley 
Sorry for the delay, we discussed this internally and we raised the priority of this feature.
So I think this is probably gonna be implemented in the next few weeks (1 or 2 ).
Actually it is not only missing in the ingress controller but it also needs to be implemented in the client-native library (what the ingress controller is using)

**Comment by beazlr02** [comment]
Having tried this controller before realising the lack of http auth I then switched to https://github.com/jcmoraisjr/haproxy-ingress

**Comment by Nainterceptor** [comment]
> Hey @AlexisDuf @rossbeazley
> Sorry for the delay, we discussed this internally and we raised the priority of this feature.
> So I think this is probably gonna be implemented in the next few weeks (1 or 2 ).
> Actually it is not only missing in the ingress controller but it also needs to be implemented in the client-native library (what the ingress controller is using)

Hello, any update about this feature ?

**Comment by margarita-markova** [comment]
Dear @oktalz, @bedis, @AlexisDuf and developers,
could you please provide some information about this issue? 
It is really need for work with some tools without basic auth like Prometheus (https://prometheus.io/docs/guides/basic-auth/)

**Comment by wgebis** [comment]
Hi guys! Any news about support basic auth in haproxy ingress?

**Comment by prometherion** [comment]
:wave: all! With the latest commits (starting from c7ee422a4e943f5dfbe62ff97f75ba765397e3ed) we're going to ship this feature for the upcoming 1.5.0 release! 🚀

Once there, please, feel free to test it and close this issue, or rather, add eventually a detailed bug report.

**Comment by Mo3m3n** [comment]
This is supported from 1.5 via these [annotations](https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#authentication)

**Comment by nikell28** [comment]
Hi!
My base auth not working
Help me?

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingres
  namespace: backend
  annotations:
    ingress.kubernetes.io/auth-realm: Authentication Required
    ingress.kubernetes.io/auth-secret: basic-auth-haproxy-credentials
    ingress.kubernetes.io/auth-type: basic-auth
spec:
  rules:
  - host: *****
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hlsrs-web-svc
            port:
              number: 80
```
