### ISSUE TITLE
How to show the address of ingress

### ISSUE THREAD

**Issue by junyeong-huray** [haproxytech/kubernetes-ingress#480]
Hello

I have two ingress controllers in one k8s cluster.

one thing is `ingress-nginx` and the other is `haproxy-kubernetes-ingress`.

I use `ingress-nginx` to handle requests from the internet and it is bound to
a cloud provisioned loadbalancer which is assigned a public IP.
And I use `haproxy-kubernetes-ingress` to handle requests from the internal 
backend servers outside of the k8s cluster or from the browsers of developers
in the office. And the ingress is bound to  a cloud provisioned loadbalancer
which is assigned a private IP.

The thing is that the result of command, `kubectl get ing`, does not show the address
of ingress which is handled by `haproxy-kubernetes-ingress`..

Here is the output of kubectl (the actual domain name is masked by XXXX):

```command
$ kubectl get ing
NAME               CLASS    HOSTS                     ADDRESS                               PORTS     AGE
chase-private      <none>   chase.XXXXX                                                     80        35m
chase-public       <none>   chase.XXXXX     XXXXX.kr.lb.naverncp.com   80, 443   23m
```

The ingress controller of `chase-private` is `haproxy-kubernetes-ingress` and
the ingress controller of `chase-public` is `ingress-nginx`.

The output of `kubectl get ing/chase-private -o yaml` is here:

```yaml
$ kubectl get ing/chase-private -o yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    haproxy.org/ingress.class: haproxy
  name: chase-private
    ... omitted ...
spec:
  rules:
  - host: chase.XXXXX
    http:
      paths:
      - backend:
          service:
            name: chase
            port:
              number: 8000
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
```

Look at that `loadBalancer` is empty.

But the output of `kubectl get ing/chase-public -o yaml` shows `loadBalancer` as expected:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: chase-public
  ... omitted ...
spec:
  rules:
  - host: chase.XXXXX
    http:
      paths:
      - backend:
          service:
            name: chase
            port:
              number: 8000
        path: /
        pathType: Prefix
  tls:
  - hosts:
     ... omitted ...
status:
  loadBalancer:
    ingress:
    - hostname: XXXXXXXXXXX.kr.lb.naverncp.com
```

What can I do to make `chase-private` have the address of `loadBalancer`?
Any advice will be appreciated.

Thanks,

**Comment by junyeong-huray** [comment]
And here is the k8s manifest that is used to install haproxy-kubernetes-ingress.
It is based on the [official manifest](https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.8/deploy/haproxy-ingress.yaml) but is modified little bit.

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: haproxy-controller

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: haproxy-kubernetes-ingress
  namespace: haproxy-controller

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: haproxy-kubernetes-ingress
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - nodes
  - pods
  - services
  - namespaces
  - events
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "extensions"
  - "networking.k8s.io"
  resources:
  - ingresses
  - ingresses/status
  - ingressclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "extensions"
  - "networking.k8s.io"
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
- apiGroups:
  - core.haproxy.org
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - "discovery.k8s.io"
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: haproxy-kubernetes-ingress
  namespace: haproxy-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: haproxy-kubernetes-ingress
subjects:
- kind: ServiceAccount
  name: haproxy-kubernetes-ingress
  namespace: haproxy-controller

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-kubernetes-ingress
  namespace: haproxy-controller
data:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: ingress-default-backend
  name: haproxy-kubernetes-ingress-default-backend
  namespace: haproxy-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ingress-default-backend
  template:
    metadata:
      labels:
        run: ingress-default-backend
    spec:
      containers:
      - name: ingress-default-backend
        image: gcr.io/google_containers/defaultbackend:1.0
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: ingress-default-backend
  name: haproxy-kubernetes-ingress-default-backend
  namespace: haproxy-controller
spec:
  selector:
    run: ingress-default-backend
  ports:
  - name: port-1
    port: 8080
    protocol: TCP
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-kubernetes-ingress
  namespace: haproxy-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      run: haproxy-ingress
  template:
    metadata:
      labels:
        run: haproxy-ingress
    spec:
      serviceAccountName: haproxy-kubernetes-ingress
      containers:
      - name: haproxy-ingress
        image: haproxytech/kubernetes-ingress:1.8.4
        args:
          - --configmap=haproxy-controller/haproxy-kubernetes-ingress
          - --default-backend-service=haproxy-controller/haproxy-kubernetes-ingress-default-backend
          - --ingress.class=haproxy
          - --disable-ipv6
        securityContext:
          runAsUser:  1000
          runAsGroup: 1000
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
        resources:
          requests:
            cpu: "500m"
            memory: "50Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 1042
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: stat
          containerPort: 1024
        env:
        - name: TZ
          value: "Etc/UTC"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: haproxy-ingress
  name: haproxy-kubernetes-ingress
  namespace: haproxy-controller
  annotations:
    # this configuration must be set to make the cloud LB private
    service.beta.kubernetes.io/ncloud-load-balancer-internal: "true"
spec:
  selector:
    run: haproxy-ingress
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: stat
    port: 1024
    protocol: TCP
    targetPort: 1024

``` 

The difference is here:

```diff
--- haproxy-ingress.yaml.orig   2022-08-24 18:53:39.000000000 +0900
+++ haproxy-ingress.yaml        2022-08-19 18:27:07.000000000 +0900
@@ -163,10 +163,12 @@
       serviceAccountName: haproxy-kubernetes-ingress
       containers:
       - name: haproxy-ingress
-        image: haproxytech/kubernetes-ingress
+        image: haproxytech/kubernetes-ingress:1.8.4
         args:
           - --configmap=haproxy-controller/haproxy-kubernetes-ingress
           - --default-backend-service=haproxy-controller/haproxy-kubernetes-ingress-default-backend
+          - --ingress.class=haproxy
+          - --disable-ipv6
         securityContext:
           runAsUser:  1000
           runAsGroup: 1000
@@ -209,10 +211,13 @@
     run: haproxy-ingress
   name: haproxy-kubernetes-ingress
   namespace: haproxy-controller
+  annotations:
+    # this configuration must be set to make the cloud LB private
+    service.beta.kubernetes.io/ncloud-load-balancer-internal: "true"
 spec:
   selector:
     run: haproxy-ingress
-  type: NodePort
+  type: LoadBalancer
   ports:
   - name: http
     port: 80
```
