### ISSUE TITLE
Troubleshoot issue with whitelist in Azure vm

### ISSUE THREAD

**Issue by psapozh** [haproxytech/kubernetes-ingress#483]
Hello

We are using ingress controller version 1.6.0 inside Azure AKS. I am trying to add ingress resource that has a certain host, path and also whitelist annotation. I am setting this whitelist value to be the public ip of one of our Azure vms. What happens is from my local I try to initiate this request and I get 403 - this is expected correct behaviour because my local ip is not one of the whitelisted ips. However, then I try to initiate same request from this vm whos public ip is the one I whitelisted and from there I get 403 as well. Not sure what I am doing wrong here. I know having whitelist there does something because if I comment it out then it allows that path from all ips. Also, I dont know how to debug this. Tried looking at logs of the pods nothing obvious there.

**Comment by ivanmatmati** [comment]
Hi @psapozh , can you post your white list configuration and the resulting haproxy configuration file section with the deny clause.

**Comment by psapozh** [comment]
ok so I have actually upgraded the installation to the latest version.

But here's the Ingress

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: interopswaggerui
  namespace: interop
  annotations:
      meta.helm.sh/release-name: interopapideployment
      meta.helm.sh/release-namespace: interop
      haproxy.org/whitelist: "x.x.x.x"
      ingress.class: "haproxy"
  labels:
    app.kubernetes.io/instance: interopapideployment
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: interopapideployment
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: interopapideployment-0.1.0
spec:
  rules:
  - host: someHost.com
    http:
      paths:
        - path: /swagger-ui
          backend:
            serviceName: interopapideployment
            servicePort: 8080
```

and this is a snippet from haproxy.cfg

```
frontend http
  mode http
  bind 0.0.0.0:80 name v4
  bind :::80 name v6
  http-request set-var(txn.base) base
  http-request set-var(txn.path) path
  http-request set-var(txn.host) req.hdr(Host),field(1,:),lower
  http-request set-var(txn.host_match) var(txn.host),map(/etc/haproxy/maps/host.map)
  http-request set-var(txn.host_match) var(txn.host),regsub(^[^.]*,,),map(/etc/haproxy/maps/host.map,'') if !{ var(txn.host_match) -m found }
  http-request set-var(txn.path_match) var(txn.host_match),concat(,txn.path,),map(/etc/haproxy/maps/path-exact.map)
  http-request set-var(txn.path_match) var(txn.host_match),concat(,txn.path,),map_beg(/etc/haproxy/maps/path-prefix.map) if !{ var(txn.path_match) -m found }
  http-request deny deny_status 403 if { var(txn.path_match) -m dom 47eee10fc68d3a2e771e64481f8b735c } !{ src -f /etc/haproxy/maps/whitelist-f41f9c053c84b81407234bb7a7b30318.map }
  use_backend %[var(txn.path_match),field(1,.)]
  default_backend ingress_haproxytech-kubernetes-ingress-default-backend_http
```
