### ISSUE TITLE
Ingress class never be attach on first deployment

### ISSUE THREAD

**Issue by matholleville** [haproxytech/kubernetes-ingress#508]
Hello,

I have a problem when deploying the HAProxy ingress on one of the clusters (GKE) of my company.

The behavior is really strange. I want to deploy my ingress controller with an internal loadbalancer service.

I configure the helm chart values with the following parameters:

```yaml
kubernetes-ingress:
  controller:
    extraArgs:
      - --namespace-whitelist=my-namespace
      - --cache-resync-period=1m
    traffic:
      level: debug
      address: stdout
      format: raw
      facility: daemon
    config:
      syslog-server: "address:stdout, format: raw, facility:daemon"
      log-format: "client_address=%ci status=%ST path=%HU method=%HM"
      use-proxy-protocol: "true"
      timeout-connect: 5s
      timeout-check: 3s
      timeout-client: 50s
      timeout-server: 50s
      maxconn: "2000"
    resources:
      requests:
        cpu: 250m
        memory: 400Mi

    service:
      type: LoadBalancer
      externalTrafficPolicy: "Local"
      annotations:
        networking.gke.io/load-balancer-type: "Internal"
```

During the deployment, no problem with the pods of the ingress controller. No error in the logs.

Once the IP is retrieved from the controller service, none of my ingresses can bind to the IP of the ingress service.

So I thought that it could be because the waiting time before retrieving an IP at the service level can sometimes exceed several minutes. While digging this part, I saw that in the controller doc there was an option on the cache sync.

So I tried to lower the default value (10 minutes) to 1 minute, but it didn't fix my problem.

-----

The only "solution" I found that works is to wait for the service to recover an IP and restart the pods of the controller. Magically, when the pods are restarted, my ingresses are correctly attached to the ingress controller.

[I already opened an issue on the helm chart repo and was told to open it here](https://github.com/haproxytech/helm-charts/issues/170)
