### ISSUE TITLE
https and mqtt on same port.

### ISSUE THREAD

**Issue by leovanalphen** [haproxytech/kubernetes-ingress#516]
We are using haproxy ingress controller on GKE, and so for it works like a charm. However I now have a use-case I cannot get working.

We have an app deployment on a GKE cluster with one HAproxy ingress controller which exposes a TLS webpage on port 443 through a google load balancer. With a domain pointing to the ip: app.example.com. We also have an hivemq broker running on port 1883, exposed by haproxy through the tcp-configmap at app.example.com:1883 where haproxy does the TLS termination before sending the traffic to the broker.

Now I am being asked to change the routing of the broker. They want it to be available at mqtt.app.example.com:443 (this is for edge devices installed at customers, they want to be able to say to customers that only port 443 towards the internet to be open).

I've created a dummy ingress for the broker (to get a seperate TLS cert):

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hivemq-ingress
  annotations:
    kubernetes.io/ingress.class: haproxy
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: mqtt.app.example.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: hivemq-hivemq-mqtt
              port:
                number: 1883
  tls:
    - secretName: hivemq-ingress-tls
      hosts:
        - mqtt.app.example.com
```

and updated my controller values and tcp-configmap:

```
controller:
  kind: DaemonSet
  hostNetwork: false
  ingressClass: haproxy
  extraArgs:
    - --configmap-tcp-services=default/tcp

  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: 34.x.x.x
    annotations:
    ports:
      https: 443
    tcpPorts:
      - name: mqtt
        port: 443
        targetPort: 1883

  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: tcp
    namespace: default
  data:
    443:
      default/hivemq-hivemq-mqtt:1883:ssl
```

The problem is offcourse, port 443 is already in use for the https/webpage service so if I try to deploy this I get a port already in use error. I've been racking my brain how to get this to work, or if it is even possible. The only thing I can think of that I know would work, is starting a second haproxy ingress controller with a different LB ip, and just use that for the broker. But that would duplicate haproxy pods and the (expensive) google LB.

I'd like to match on the url, and either send the traffic to the webpage, or send it to the mq broker. But since the broker isn't http protocol I can't use the usual ingress path/host routing.

Am I missing something, or is what I want to do just not possible currently?
