### ISSUE TITLE
Different backend-config-snippet on multiple ingress objects targeting same service can cause unnecessary reloads

### ISSUE THREAD

**Issue by sbbtoic** [haproxytech/kubernetes-ingress#517]
### Issue description

Defining multiple ingress objects (each with its own unique backend-config-snippets) targeting same service object can trigger unnecessary ingress-controller reloads.

Kubernetes version: 1.25.3
HAProxy Ingress controller version:  1.9.0
HAProxy Ingress controller Helm chart version:  1.25.1

#### Scenario

staging2 deployment is running web application where some paths should be handled differently.

Common use case in our environment  staging web service that needs to have basic auth enabled alongside some custom ACLs that can't be replicated via standard haproxy.org annotations. 
Same service is also hosting some static files and /api/ suburls that should be excluded from basic-auth.

Simplified ingress objects

**Exclude from basic-auth and without backend-config-snippet**
```yaml
---
apiVersion: "networking.k8s.io/v1"
kind: Ingress
metadata:
  name: staging2-api
  namespace: apps
spec:
  ingressClassName: haproxy-test
  tls:
    - hosts:
        - staging2-api
      secretName: apps-cert
  rules:
    - host: "staging2-api"
      http:
        paths:
          # static files (exclude form basic auth)
          - path: "/_next/"
            pathType: Prefix
            backend:
              service:
                name: staging2-httpbin
                port:
                  number: 80
          # api route (exclude from basic auth)
          - path: "/api/"
            pathType: Prefix
            backend:
              service:
                name: staging2-httpbin
                port:
                  number: 80
```

**Include basic-auth and custom backend-config-snippet**
```yaml
---
apiVersion: "networking.k8s.io/v1"
kind: Ingress
metadata:
  name: staging2
  namespace: apps
  annotations:
    haproxy.org/auth-type: basic-auth
    haproxy.org/auth-secret: ingress/staging-secret
    haproxy.org/backend-config-snippet: |
      acl feed_path path_reg ^/([\w-]+)/feed$
      http-request redirect code 301 location %[path,regsub(\"^/([\w-]+)/feed\",\"/feed/\1\",)] if feed_path
      acl kat_feed_path path_reg ^/kategorija/([\w-]+)/feed$
      http-request redirect code 301 location %[path,regsub(\"^/kategorija/([\w-]+)/feed\",\"/feed/\1\",)] if kat_feed_path
      acl CDN hdr(X-CF-CDN-ID) -m found
      acl static_path path_beg /_next
      http-request redirect code 301 location http://staging2%[capture.req.uri] if CDN !static_path
spec:
  ingressClassName: haproxy-test
  tls:
    - hosts:
        - staging2
      secretName: apps-cert
  rules:
    - host: "staging2"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: staging2-httpbin
                port:
                  number: 80
```

Having this configuration active in the cluster, ingress-controller will react to any service object change (even unrelated to these ingress objects) within the apps namespace and will force reload HAProxy process.

Example debug log lines from ingress controler

```
2023-01-17T09:18:35+01:00 2023/01/17 08:18:35 DEBUG   service/service.go:150 Service 'apps/staging2-httpbin': backend 'apps_staging2-httpbin_http' config-snippet updated: [[acl feed_path path_reg ^/([\w-]+)/feed$ http-request redirect code 301 location %[path,regsub(\"^/([\w-]+)/feed\",\"/feed/\1\",)] if feed_path acl kat_feed_path path_reg ^/kategorija/([\w-]+)/feed$ http-request redirect code 301 location %[path,regsub(\"^/kategorija/([\w-]+)/feed\",\"/feed/\1\",)] if kat_feed_path acl CDN hdr(X-CF-CDN-ID) -m found acl static_path path_beg /_next http-request redirect code 301 location http://staging2%[capture.req.uri] if CDN !static_path] != <nil slice>]
2023-01-17T09:18:35+01:00 Reload required
2023-01-17T09:18:35+01:00 2023/01/17 08:18:35 DEBUG   service/service.go:150 Service 'apps/staging2-httpbin': backend 'apps_staging2-httpbin_http' config-snippet updated: [<nil slice> != [acl feed_path path_reg ^/([\w-]+)/feed$ http-request redirect code 301 location %[path,regsub(\"^/([\w-]+)/feed\",\"/feed/\1\",)] if feed_path acl kat_feed_path path_reg ^/kategorija/([\w-]+)/feed$ http-request redirect code 301 location %[path,regsub(\"^/kategorija/([\w-]+)/feed\",\"/feed/\1\",)] if kat_feed_path acl CDN hdr(X-CF-CDN-ID) -m found acl static_path path_beg /_next http-request redirect code 301 location http://staging2%[capture.req.uri] if CDN !static_path]]
2023-01-17T09:18:35+01:00 Reload required
```

This issue is reproducible by deploying new service object (unrelated to this one), or scaling any of the deployments in the same namespace which will modify service endpoints (even if they are unrelated to this one).

I suspect the issue is because 2 different ingress objects are targeting same service object, and controller evaluates the backend-config-snippet for each ingress object to see what should be placed in resulting (same) HAProxy backend configuration. This causes flapping of the backend-config-snippet configuration setting the reload variable to true in [this function](https://github.com/haproxytech/kubernetes-ingress/blob/master/pkg/service/service.go#L117) even though there are no actual changes in the merged config.

In some cases backend-config-snippet can be completely lost if there is another ingress object without backend-config-snippet annotation later in the order of evaluation.

When we define identical backend-config-snippet to all ingress objects connected to same service this issue is not reproducible. This however is adding complexity in maintaining those ingress objects as each new line in backend-config-snippet should be replicated for all ingress objects.

I understand that the service object supports the backend-config-snippet annotation as well and this would centralize the above mentioned work-around. However, in some deployment scenarios this is not possible, either for reasons of shared configuration responsibility (Ops team maintaining ingress objects, while Dev team maintains service objects), or in cases where some app Helm charts don't have implemented additional service annotation capabilities.

On busy clusters where HPA policies are constantly scaling deployments we have observed reloads as often as every minute.
While the reload will not drop the connections, it will drastically hinder available throughput of requests.

This is a result of running 

`siege -c 100 -i https://staging-nginx-test.domain.com`

on 4 replica Nginx deployment running behind HAProxy Ingress controller
![image](https://user-images.githubusercontent.com/116298668/212864116-8dea06e4-e6ed-462a-ad85-36145b22f89e.png)

I would expect almost flat graph running constantly at 600 resp/s 

### Steps to reproduce the issue

This issue is reproducible running on local [kind](https://kind.sigs.k8s.io/) cluster. 

[haproxy-ingress-reproduce.tar.gz](https://github.com/haproxytech/kubernetes-ingress/files/10433712/haproxy-ingress-reproduce.tar.gz)

Attaching to this issue is an archive containing all required yaml files for deploying kind kubernetes cluster, HAProxy ingress controler as ClusterIP (as we can't have multiple replicas on kind exposing their container ports), sample dummy applications and services are deployed via [helmfile](https://helmfile.readthedocs.io/en/latest/), broken and working ingress objects.

#### Environment setup

Deploy local kind cluster and HAProxy ingress controler with sample application and dummy ssl cert for ingress objects.

1. Unpack the archive above
2. kind create cluster --config=kind-cluster.yaml
3. helmfile --file helmfile-haproxy.yml apply
4. helmfile --file helmfile-apps.yml apply
5. kubectl apply -f cert.yaml

#### expected  behaviour (All ingress objects targeting single service have identical backend config snippet)

1. kubectl apply -f ingress-objects-normal/

bug is not triggered when deploying new service objects not having any ingress objects at all
cycle between commands (wait for 15s between commands while looking at the ingress controller logs)

2. helmfile --file helmfile-apps-unrelated.yml apply
3. helmfile --file helmfile-apps-unrelated.yml delete

Ingress controller is not reacting to adding new services in namespace

bug  is not triggered when sacaling existing deployments having defined ingress objects
cycle between commands (wait for 15s between commands while looking at the ingress controller logs)

4. kubectl -n apps scale deployment staging1-httpbin --replicas=2
5. kubectl -n apps scale deployment staging1-httpbin --replicas=1

Ingress controller is just adding additional endpoints in existing backend server slots without reloading the HAProxy process

#### bug (Multiple ingress objects targeting same service having different backend-config snippet)

1. kubectl apply -f ingress-objects/

bug can be triggered by deploying new service objects not having any ingress objects at all
cycle between commands (wait for 15s between commands while looking at the ingress controller logs)

2. helmfile --file helmfile-apps-unrelated.yml apply
3. helmfile --file helmfile-apps-unrelated.yml delete

Ingress controller re-evaluates all services in namespace triggering backend-config-snippet flaping and executing full process reload.

bug can be triggered by scaling existing deployments having defined ingress objects
cycle between commands (wait for 15s between commands while looking at the ingress controller logs)

4. kubectl -n apps scale deployment staging1-httpbin --replicas=2
5. kubectl -n apps scale deployment staging1-httpbin --replicas=1

Ingress controller re-evaluates all services in namespace triggering backend-config-snippet flaping and executing full process reload.

#### cleanup
kind delete cluster --name kind-haproxy

### Proposed solution

backend-config-snippets from multiple ingress objects should be merged and re-evaluated for reload after all ingress objects for given service are processed.

Unfortunately my GO skills are practically non-existing so I'm unable to propose a solution with the proper codebase or issue a pull request. However, I am willing to assist with testing and providing any other information required.
