### ISSUE TITLE
HAproxy Ingress controller takes is not assigning external IP to ingress

### ISSUE THREAD

**Issue by mozz-lx** [haproxytech/kubernetes-ingress#526]
Hello Team.

I'm trying to update from HAproxy ingress controller `1.7.2` to `1.7.12` when I realize that the new version is not assigning the haproxy ingress controller service endpoint address to the ingress.

 In this example, I created the ingress and it has been there for 6 hours with the IP being assigned.
![image](https://user-images.githubusercontent.com/69945641/222446769-0d0c59b8-2f3d-4578-8994-b0bf4c0efca9.png)

Only after restarting one of the Ingress controllers pods the endpoint is assigned.
![image](https://user-images.githubusercontent.com/69945641/222449431-b6d63a68-dd0e-4c4b-b295-d9c63f1d8bed.png)

This is my ingress configuration.
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test1
  namespace: XXXX
  annotations:
    external-dns.alpha.kubernetes.io/hostname: XXXXXXXX
  labels:
    environment: dev
spec:
  defaultBackend:
    service:
      name: XXXXXXXXXX
      port:
        number: 8080
  rules:
    - host: XXXXXXXXXXXXXX
      http:
        paths:
          - pathType: Prefix
            path: /test1
            backend:
              service:
                name: test1-service
                port:
                  number: 80

```
I have done the same test with different scenarios getting the same behavior. 

Doing other changes to the ingress is reflected as expected, but all newly created ingress is getting stuck waiting for the endpoint to be added

Not sure if that behavior can be associated with this bug fix --> https://github.com/haproxytech/kubernetes-ingress/commit/ea7b2437feb10a13e5f8ac2c21f045e2167082c2

This is the only error I saw this error after restarting one of the haproxy ingress controller pods to get the endpoint configured.
```
2023/03/02 13:29:10 ERROR   ingress/status.go:26 failed to update LoadBalancer status of ingress ott/test1: Operation cannot be fulfilled on ingresses.networking.k8s.io "test1": the object has been modified; please apply your changes to the latest version and try again
```
