### ISSUE TITLE
FEAT/ Apply TCP mode loadbalance algorithm  to services

### ISSUE THREAD

**Issue by benm-stm** [haproxytech/kubernetes-ingress#530]
Add a loadbalancing algorithm in the tcp-configmap this way
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-ingress
  namespace: default
  annotations:
    haproxytech/load-balance: leastconn
data:
  "1025": namespace/svc:8080
```
This latter one will be applied to all tcp services in the tcp-configmap

**Comment by benm-stm** [comment]
Or better, imbed load-balance algorithm in the data section per service
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-ingress
  namespace: default
data:
  "1025": namespace/svc:8080:load-balance=leastconn
  "1026": namespace/svc:8081:load-balance=roundrobin
```
