### ISSUE TITLE
Feature Request: auth proxy support

### ISSUE THREAD

**Issue by mateuszdrab** [haproxytech/kubernetes-ingress#531]
Hi

Haproxy is my external facing ingress controller of choise; however, for purpose of oauth2 authentication, I've been 'daisy-chaining' an Nginx Ingress Controller which is configured with duplicate ingresses to allow oauth2 authentication via oauth2-proxy. This is achieved with the annotations:
```
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
```

Unfortunately, it does not appear that this ingress controller supports it - but I'd like to do away with jumping between controllers.
Is it feasible to implement support for this?
It is supported by a similar project at https://github.com/jcmoraisjr/haproxy-ingress

Thanks

**Comment by ivanmatmati** [comment]
Hi @mateuszdrab , we might consider that in the future. Your request has been labeled as enhancement.

**Comment by Zempashi** [comment]
I managed to get it working. That's definitely a work-around; but here the receip:
1/ Assemble the lua code in a configmap, I use a makefile for that:
```
lua:
        kubectl create configmap -n ingress-system haproxy-lua --dry-run=client -o yaml \
        --from-literal=http.lua="$$(curl https://raw.githubusercontent.com/haproxytech/haproxy-lua-http/master/http.lua)" \
        --from-literal=auth-request.lua="$$(curl https://raw.githubusercontent.com/TimWolla/haproxy-auth-request/main/auth-request.lua)" \
        --from-literal=json.lua="$$(curl https://raw.githubusercontent.com/rxi/json.lua/master/json.lua)" \
        > haproxy-lua.configmap.yaml
        #kubectl apply -f heproxy-lua.configmap.yaml
```

Modify the deployment; (I used helm) here the added values:

```
controller
    extraVolumes:
    - name: haproxy-lua
      configMap:
        name: haproxy-lua
        items:
        - key: json.lua
          path: json.lua
        - key: http.lua
          path: haproxy-lua-http/http.lua
        - key: auth-request.lua
          path: auth-request.lua
    extraVolumeMounts:
    - name: haproxy-lua
      mountPath: /usr/share/haproxy
    config:
      global-config-snippet: |
        lua-prepend-path /usr/share/haproxy/?/http.lua
        lua-prepend-path /usr/share/haproxy/?.lua
        lua-load /usr/share/haproxy/auth-request.lua
```

Now you need to modify the ingresses you want to protect with this added annotation
```        
haproxy.org/backend-config-snippet: |
            http-request lua.auth-intercept oauth2-proxy_oauth2-proxy_http  /oauth2/auth  HEAD    *        -        -
            http-request redirect code 301 location http://%[hdr(host)]/oauth2/start?rd=%[capture.req.uri] if ! { var(txn.auth_response_successful) -m bool }
```

Note that I (also) use oauth2-proxy, and expose it via an ingress, so I have a backend (`oauth2-proxy_oauth2-proxy_http`) already created, but I guess that a backend CRD (https://www.haproxy.com/documentation/kubernetes/latest/community/configuration-reference/custom-resources/backend/) should do the trick as well

Reference:
- https://github.com/TimWolla/haproxy-auth-request

PS: I just read a know limitation of the script I used "The backend must not be using TLS."; seeing the annotation you used, this might me a problem
