### ISSUE TITLE
[BUG] Duplicated backend config snippets for multi-host ingress

### ISSUE THREAD

**Issue by mecampbellsoup** [haproxytech/kubernetes-ingress#534]
We recently upgraded our IC from 1.9.1 to 1.9.5.

We are pretty sure [this commit](https://github.com/haproxytech/kubernetes-ingress/commit/90f9d1b022629153f5d3efd0bc8b7f45d4312ead#diff-c79215636af0d1a1acac73010b67e6320182ffab033d80152708d31adfcf71f7R86) introduced the bug I am about to describe:

https://github.com/haproxytech/kubernetes-ingress/commit/90f9d1b022629153f5d3efd0bc8b7f45d4312ead

We have an ingress with 2 hostnames, ingressing the same service, as follows:

```yaml
  rules:
  - host: grafana.coreweave.com
    http:
      paths:
      - backend:
          service:
            name: grafana-tenant
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: admin-grafana.coreweave.com
    http:
      paths:
      - backend:
          service:
            name: grafana-tenant
            port:
              number: 80
        path: /
        pathType: Prefix
```

Now, the backend config snippet is being duplicated as you can see:

```yaml
/usr/local/share/lua/5.3 $ cat /etc/haproxy/haproxy.cfg  | grep grafana -A 20
backend grafana-tenant-staging_grafana-tenant-staging_service
  mode http
  balance roundrobin
  option forwardfor
  no option abortonclose
  default-server check
  ###_config-snippet_### BEGIN
  http-request lua.cached-auth if !{ req.hdr(host) -m sub admin }
  http-request redirect location https://cloud.staging.coreweave.com/login?r=https://%[req.hdr(host)]%[pathq] if !{ req.hdr(x-consumer-username) -m found } !{ req.hdr(host) -m sub admin }
  http-request lua.cached-auth if !{ req.hdr(host) -m sub admin }
  http-request redirect location https://cloud.staging.coreweave.com/login?r=https://%[req.hdr(host)]%[pathq] if !{ req.hdr(x-consumer-username) -m found } !{ req.hdr(host) -m sub admin }
  ###_config-snippet_### END
  server SRV_1 10.144.113.78:3000 enabled
```

If your config snippets mutate some state, e.g. ` txn.http:req_del_header("authorization")`, then it is not idempotent and this duplication is very, very bad.

I would never expect two hosts in a single ingress to cause duplicated snippets.

How does https://github.com/haproxytech/kubernetes-ingress/commit/213c160993fccd158a4be81c1528b3ba2cbe0b12 not have any corresponding test coverage?
