### ISSUE TITLE
haproxy keeps serving default ssl.

### ISSUE THREAD

**Issue by PascalKu** [haproxytech/kubernetes-ingress#55]
Hey there,

I am using haproxy, cert-manager and let's encrypt in my k8s tech stack.

Whenever I am deploying an ingress with another domain like this:

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  namespace: cloud-system
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: "http01"
spec:
  tls:
    - hosts:
        - api.example.me
      secretName: api-example-me-cert
  rules:
    - host: api.example.me
      http:
        paths:
          - path: /
            backend:
              serviceName: "api-service"
              servicePort: 80
```

My haproxy setup always returns the default cert (setted up in haproxy-ingress deployment as argument like : --default-ssl-certificate=default/example-tld-tls). And I don't know why.

**Comment by PascalKu** [comment]
The cert is valid! and stored in the given secret.

**Comment by oktalz** [comment]
Hi, @PascalKu 

you can expect fix for this in next few days.
I'll notify you when this will be ready

**Comment by git001** [comment]
Looks like it's the same issue as #44 #30

**Comment by oktalz** [comment]
@git001 yes, seems so, 

commit were already up on Friday, but today a new version v1.2.0 is released.
please note that if you define secret in ingress object, 
you do not need to define default certificate in order to use https

**Comment by oktalz** [comment]
format that controller expects is something like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: app
 namespace: default
 annotations:
   ingress.class: haproxy
spec:
 tls:
  - hosts:
	- foo.bar
	secretName: default/tls-secret
 rules:
 - host: foo.bar
   http:
	 paths:
              ......
```
regarding secret format, it is same as for default secret
https://github.com/haproxytech/kubernetes-ingress/tree/master/documentation#tls-secret

**Comment by oktalz** [comment]
please test with v1.2.1
v1.2.0 has an annoying bug

**Comment by yann-soubeyrand** [comment]
Hi,

I did test v1.2.1 and noticed two problems:
- You need to prepend ingress' spec.tls[].secretName with secret's namespace which prevents cert-manager from working (Nginx ingress controller and cert-manager expect the secret name to not be qualified with their namespace).
- You need to restart the controller for it to take the newly created secret (when using cert-manager) into account.

**Comment by oktalz** [comment]
hi @yann-soubeyrand, thx for the info.

I'll check for both of those things, definitely this is not desired behavior.

**Comment by oktalz** [comment]
Hi @yann-soubeyrand 
can you chek again for `spec.tls[].secretName ` you mentioned
because you have two options here:
either say
```
secretName: secret-namespace/tls-secret
```
or to use 
```
secretName: tls-secret
```
that will then presume that secret is in the same namespace as ingress

https://github.com/haproxytech/kubernetes-ingress/blob/54adbd37a8a60615be2f9e2aebc4dc336c3469ea/controller-https.go#L123-L130

regarding restart, I'm still looking into it

**Comment by oktalz** [comment]
@yann-soubeyrand I found the issue
its just right after the code I mentioned,
latest commit f989734 has the fix for it.

**Comment by yann-soubeyrand** [comment]
@oktalz Thanks, I'll try to test it tomorrow ;-)

**Comment by yann-soubeyrand** [comment]
@oktalz it's still not working with 1.2.2.

Here are the steps to reproduce on an EKS cluster:
1. Install cert-manager:
  - `kubectl create namespace cert-manager`
  - `kubectl label namespace cert-manager certmanager.k8s.io/disable-validation=true`
  - `kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v0.10.0/cert-manager.yaml`
  - put the following content in a file named letsencrypt.yaml (change the email):
```
apiVersion: "certmanager.k8s.io/v1alpha1"
kind: "ClusterIssuer"
metadata:
  name: "letsencrypt"
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "mail@example.com"
    privateKeySecretRef:
      name: "letsencrypt"
    solvers:
    - http01:
        ingress: {}
```
  - execute `kubectl apply -f letsencrypt.yaml`
2. Install HAProxy ingress controller:
  - `kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/master/deploy/haproxy-ingress.yaml`
  - edit the service to set its type to LoadBalancer: `kubectl -n haproxy-controller edit service haproxy-ingress`
  - make a route53 record pointing to the newly created load balancer
3. Create a test application:
  - execute `kubectl create ns echo-server`
  - put the following YAML into a file named `echo-server.yaml` (set the host in the ingress to the route53 record set previously)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  labels:
    app.kubernetes.io/name: echo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: echo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo-server
    spec:
      containers:
      - name: echo-server
        image: jmalloc/echo-server
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
  labels:
    app.kubernetes.io/name: echo-server
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app.kubernetes.io/name: echo-server
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo-server
spec:
  rules:
  - host: <route53-record>
    http:
      paths:
      - backend:
          serviceName: echo-server
          servicePort: 80
        path: /
```
  - execute `kubectl -n echo-server apply -f echo-server.yaml`
4. The HAProxy ingress controller does an HTTPS redirection whereas it should not (there is no default certificate and this is an HTTP ingress):
  - execute `curl -I http://<route53-domain>/`
```
HTTP/1.1 302 Found
content-length: 0
location: https://<route53-domain>/
cache-control: no-cache
```
5. Disable HTTPS redirection:
  - execute `kubectl edit configmap haproxy-configmap` and add the following content at the end of the file
```
data: 
  ssl-redirect: "OFF"
```
6. The HTTP ingress does not work:
  - execute `curl -I http://<route53-domain>/`
```
HTTP/1.1 503 Service Unavailable
content-length: 107
cache-control: no-cache
content-type: text/html
connection: close
```
7. Switch the ingress to HTTPS:
  - add the following content at the end of echo-server.yaml (change the host):
```
  tls:
  - hosts:
    - <route53-host>
    secretName: echo-server-tls
```
  - add the following content in the metadata section of the ingress
```
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt
```
  - execute `kubectl -n echo-server apply -f echo-server.yaml`
8. Verify that the certificate as been issued correctly:
  - execute `kubectl -n echo-server wait --for=condition=Ready --timeout=300s certificate/echo-server-tls`
  - execute `kubectl -n echo-server get secrets echo-server-tls -o json | jq -r '.data."tls.crt"' | base64 -d | openssl x509 -text -noout`
9. Check the ingress:
  - execute `curl https://<route53-domain>/`
```
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```
10. Install NGINX ingress controller:
  - execute
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/mandatory.yaml`
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/aws/service-l4.yaml`
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/aws/patch-configmap-l4.yaml`
  - switch the Route53 record to the newly created load balancer
11. Check the ingress:
  - execute `curl https://<route53-domain>/`
```
Request served by echo-server-6cdf5c7588-qvlw2

HTTP/1.1 GET /

Host: <route53-domain>
X-Request-Id: be9cd7b39d610abebd29d594141d88ea
X-Real-Ip: <redacted>
Accept: */*
User-Agent: curl/7.65.3
X-Forwarded-For: <redacted>
X-Forwarded-Host: <route53-domain>
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Original-Uri: /
X-Scheme: https
```
