### ISSUE TITLE
CSS and js file is not rendering - HAproxy Ingress

### ISSUE THREAD

**Issue by hari1083625** [haproxytech/kubernetes-ingress#555]
Hi,
I had setup the haproxy ingress controller. But the CSS and js file is not rendering.
Note:- If I deploy any non-js application its working fine.
```
apiVersion: [networking.k8s.io/v1](http://networking.k8s.io/v1)
kind: Ingress
metadata:
  name: ingress-controller
  annotations:
    [haproxy.org/check](http://haproxy.org/check): "true"
    [haproxy.org/check-http](http://haproxy.org/check-http): "/help"
spec:
  rules:
  - host: [haproxy-ingress.nxt-insights.com](http://haproxy-ingress.nxt-insights.com/)
    http:
      paths:
      - path: /help
        pathType: Prefix
        backend:
          service:
            name: nxthelp-nxthelpdoc-register-app
            port:
              number: 80
```
