### ISSUE TITLE
Possibility to add custom parameters in automatically generated backend

### ISSUE THREAD

**Issue by nv1-0** [haproxytech/kubernetes-ingress#563]
As we create an ingress resource currently. The backend service added is resolved by controller and added to haproxy.cfg in pod with some haproxy parameters. 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-ingress
  namespace: redis
spec:
  ingressClassName: haproxy
  rules:
  - http:
      paths:
      - backend:
          service:
            name: redis-redis-cluster
            port:
              number: 6379
        path: /
        pathType: Prefix
```

For e.g for above ingress the config created for backend is somewhat like

`server srv001 10.4.125.92:6379 weight 1 check inter 2s`
`server srv001 10.4.125.93:6379 weight 1 check inter 2s`
`server srv001 10.4.125.94:6379 weight 1 check inter 2s`

Here as we see **weight 1 check inter 2s** are added by controller. Now if I want to add other key like **on-marked-up shutdown-backup-sessions** in the server configuration how can I pass it through my ingress resource so that It can be added to same backend and all servers within that backend?

**Comment by fabianonunes** [comment]
You can use a [Backend CRD](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/custom-resources.md#backend):


```yaml
apiVersion: "core.haproxy.org/v1alpha2"
kind: Backend
metadata:
  name: mybackend
spec:
  config:
    default_server:
      on-marked-up: shutdown-backup-sessions
```
