### ISSUE TITLE
setting ssl-redirect: "true" on AWS results in too many redirects

### ISSUE THREAD

**Issue by sshhawwnn** [haproxytech/kubernetes-ingress#572]
I am getting this issue where I don't face in Azure but only on AWS.

Running on EKS v1.27

Here's are the steps that I did.
```
helm repo update
helm install kubernetes-ingress haproxytech/kubernetes-ingress --create-namespace --namespace kube-system --set installCRDs=true --set controller.service.type=LoadBalancer --values config-aws.yaml
```

AWS NLB Config
```
controller:
    service:
        type: LoadBalancer
        externalTrafficPolicy: Local
        enableHttp: false
        targetPorts:
            https: http
        annotations:
            external-dns.alpha.kubernetes.io/hostname: xxx.example.com # Replace value
            service.beta.kubernetes.io/aws-load-balancer-name: xxxexample # Replace value
            service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
            service.beta.kubernetes.io/aws-load-balancer-type: external
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: xxxarn # Replace value
            service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-2-Res-2021-06
            service.beta.kubernetes.io/aws-load-balancer-alpn-policy: HTTP2Preferred
            service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
```

This is the Ingress that I tried with ssl-redirect=true. If I omit the ssl-redirect, it will work with both http and https except that the http does not redirect. But If i enable it, it will get too many redirect error.
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-2048
  namespace: game-2048
  annotations:
    haproxy.org/load-balance: "roundrobin"
    haproxy.org/ssl-redirect: "true"
    haproxy.org/ssl-redirect-code: "301"
spec:
  ingressClassName: haproxy
  rules:
  - host: xxx.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: service-2048
            port: 
              number: 80
```

https://www.haproxy.com/documentation/kubernetes/latest/community/install/aws/
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.6/guide/service/annotations/
