### ISSUE TITLE
HA Proxy Ingress on AWS EKS with classic loadbalancer

### ISSUE THREAD

**Issue by awesomeinsight** [haproxytech/kubernetes-ingress#576]
We're using HA Proxy Ingress (helm-chart version 1.29.2) and enabled the proxy protocol on the ELB itself for our https listener. But from time to time these settings disappear from the ELB and proxy protocol is disabled again.
On the HAProxy side we have the following settings ... 

Ingress:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    haproxy.org/ssl-redirect: "true"
    haproxy.org/forwarded-for: "true"
```

Proxy-Protocol related setting in configmap:
```yaml
...
 proxy-protocol: "0.0.0.0/0"
...
```

kubernetes-Ingress service:
![image](https://github.com/haproxytech/kubernetes-ingress/assets/59055341/ecba69f8-463a-49d0-9aec-0eba7f260393)

We also used the annotation service.beta.kubernetes.io/aws-load-balancer-proxy-protocol = "*" once on the ingress service but this had the drawback that every listener gets the proxy protocol enabled. We don't want to have the setting for our tcp service and therefore disabled it for this listener and also here we had the behavior that the setting has  been reset without changing something on our side (proxy protocol was enabled again for the tcp service). Do you guys have an idea why this proxy-protocol settings are jump back and forth from time to time?
