### ISSUE TITLE
Protocol HTTP is not supported

### ISSUE THREAD

**Issue by faresherhar** [haproxytech/kubernetes-ingress#578]
### Issue

The GatewayClass is created with success `Ready: True`. The Gateway with TCP protocol works fine, along with TCPRoute. When creating The Gateway with HTTP protocol, no IP address is assigned to the Gateway, and in the description, it says `protocol HTTP is not supported`.

![Screenshot from 2023-10-03 16-16-52](https://github.com/haproxytech/kubernetes-ingress/assets/102948288/b708e675-add4-412c-8529-9b67fc07743f)

We've spent quite a time already troubleshooting, and still don't have any clue of the issue.
So my question is, is this message legited, and the protocol is not yet supported by the HAProxy Kubernetes Controller (because I don't see it either on the documentation), or is it a false manupulation of our part ?

Thanks for your help.

### Description

We're working on Argo Rollout, with HAProxy, and for that we're installing Gateway API.

As the [Documentation for HAProxy Kubernetes Ingress Controller 1.10 ](https://www.haproxy.com/documentation/kubernetes/latest/usage/gateway-api/install-gateway-api-components/) explains, we're using the [Experimental v0.0.5 of Gateway API](https://github.com/kubernetes-sigs/gateway-api/tree/v0.5.1), while following the [Gateway API v0.0.5 Examples](https://github.com/kubernetes-sigs/gateway-api/tree/v0.5.1/examples/experimental/v1alpha2).

> Environment

* Ubuntu 20.4, Kubernetes 1.22, HAProxy Controller Helm Chart 1.33.0

> Gateway API Manifests

```yaml
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: haproxy-ingress-gatewayclass
spec:
  controllerName: haproxy.org/gateway-controller
```

```yaml
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: gateway-tcp
  namespace: testapp
spec:
  gatewayClassName: haproxy-ingress-gatewayclass
  listeners:
  - name: listener1
    protocol: TCP
    port: 8000
    allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute

---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: route-tcp
  namespace: testapp
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway-tcp
      namespace: testaapp
  rules:
  - backendRefs:
    - group: ''
      kind: Service
      name: testapp
      port: 8080
```

```yaml
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: gateway-http
  namespace: testapp
spec:
  gatewayClassName: haproxy-ingress-gatewayclass
  listeners:
  - name: http
    protocol: HTTP
    port: 8000

---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: route-http
  namespace: testapp
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway-http
      namespace: testaapp
  hostnames:
  - XXXXX
  rules:
  - matches:
    - path:
        type: PathPrefix
  	value: /
    backendRefs:
    - group: ''
      kind: Service
      name: testapp
      port: 8080
```
