### ISSUE TITLE
Falls back to HTTP-over-443 if the ConfigMap specified through --configmap is missing (even with --disable-http option)

### ISSUE THREAD

**Issue by VelorumS** [haproxytech/kubernetes-ingress#596]
Using a non-existent ConfigMap `haproxy-controller/haproxy-kubernetes-ingress-wrong`:

```
      containers:
        - name: kubernetes-ingress-controller
          image: "haproxytech/kubernetes-ingress:1.10.10"
          imagePullPolicy: IfNotPresent
          args:
            - --configmap=haproxy-controller/haproxy-kubernetes-ingress-wrong
            - --disable-http
```

And the `curl http://<my-domain>:443/myapp` gets the response in clear from my server that's behind haproxy.

I expected it to fail to start without a ConfigMap or at least to not serve HTTP in any form (and especially over 443) when the `--disable-http` is set.
