### ISSUE TITLE
ingress.class implimented?

### ISSUE THREAD

**Issue by AlecTroemel** [haproxytech/kubernetes-ingress#6]
It looks like the haproxy ingress controller is not honoring any "ingress.class" config. From this file --> https://github.com/haproxytech/kubernetes-ingress/blob/6782495dcc6a074e2cd48c04617b7505a546afe4/annotations.go#L123 

I would think this configmap would set the "ingress.class" 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name:  CONFIGMAP_NAME
data:
  ingress.class: MY_CLASS
```

However from the logs it looks like the controller is trying to setup servers for everything in my cluster.. Is this supported yet?

**Comment by oktalz** [comment]
Hi, 
support for ingress.class will be added in the next release of controller

**Comment by oktalz** [comment]
Hi, 
please see the latest build v1.0.1, that has support for `ingress.class`.

In order to use this, annotations on ingress can be used
```
kind: Ingress
metadata:
 name: ingress_name
 namespace: ingress_namespace
 annotations:
   kubernetes.io/ingress.class: haproxy
```
- ingress that does not have that annotation, will be used, only ones that have different value in it will be omitted
- if we want to use different name for class, you can define ingress.class argument on image image
