### ISSUE TITLE
binding to privileged port fail

### ISSUE THREAD

**Issue by owanio1992** [haproxytech/kubernetes-ingress#607]
hello
I am using helm install 1.10.10 version ingress 
and change value 
```
controller:
  containerPort:
    http: 80
    https: 443
    stat: 1024
  unprivileged: true
  allowPrivilegeEscalation: true
```

but will get error
```
s6-overlay-preinit: fatal: unable to chown /var/run/s6: Operation not permitted
```

and I add `CHOWN` to securityContext.capabilities.add can fix this issue
hope can update this config to helm 
thank very much
