### ISSUE TITLE
Deleting an ingress with multiple rules deletes only one rule in haproxy.cfg

### ISSUE THREAD

**Issue by ejez** [haproxytech/kubernetes-ingress#61]
Deleting an ingress with multiple rules deletes only one rule in haproxy.cfg, other rules are not deleted.
example: `test-ingress.yaml`
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: default
spec:
  rules:
  - host: example.net
    http:
      paths:
      - path: /
        backend:
          serviceName: my-backend
          servicePort: 80
  - host: sub.example.net
    http:
      paths:
      - path: /
        backend:
          serviceName: my-backend
          servicePort: 80
```
`kubectl apply -f test-ingress.yaml`
```bash
kubectl -n haproxy-controller exec $(kubectl -n haproxy-controller get pods -l run=haproxy-ingress --no-headers -o custom-columns=":metadata.name") -- cat /etc/haproxy/haproxy.cfg
```
then:
`kubectl delete -f test-ingress.yaml`
```bash
kubectl -n haproxy-controller exec $(kubectl -n haproxy-controller get pods -l run=haproxy-ingress --no-headers -o custom-columns=":metadata.name") -- cat /etc/haproxy/haproxy.cfg
```
rule for "sub.example.net" is not deleted in /etc/haproxy/haproxy.cfg
