### ISSUE TITLE
Fails to start when run as non-root

### ISSUE THREAD

**Issue by chrismilson** [haproxytech/kubernetes-ingress#629]
I upgraded to the latest version of the controller recently and the pods started failing with:

```
s6-overlay-suexec: fatal: unable to setgid to root: Operation not permitted
```

My Deployment looks like:

```
kind: Deployment
spec:
  template:
    spec:
      containers:
      - name: haproxy-ingress
        ...
        securityContext:
          runAsNonRoot: true
          runAsUser:  1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
          seccompProfile:
            type: RuntimeDefault
```

And my belief is that perhaps the upgrade of s6 to major version 3 (since 67db961) may be related to this.
