### ISSUE TITLE
Access logs settings get overridden if using a Global Custom Resource

### ISSUE THREAD

**Issue by apalmatier** [haproxytech/kubernetes-ingress#633]
While normally you can set access logs via either the config section, or the dedicated logging section in the values files such as
```
controller:
  config:
    syslog-server: "address:stdout, format: raw, facility:local0"
```
or
```
controller:
  logging:
    traffic:
      address: stdout
      format: raw
      facility: local0
```

if you happen to try using the [Global Custom Resource](https://www.haproxy.com/documentation/kubernetes-ingress/community/configuration-reference/global-crd/), the access logs will mysteriously vanish. Only to return if you happen to read through the CRD and realize there's a secret `log_targets` field that you must include additionally, such as
```
apiVersion: "core.haproxy.org/v1alpha2"
kind: Global
metadata:
  name: global
spec:
  log_targets:
  - address: stdout
    format: raw
    facility: local0
    level: debug
```

This isn't documented anywhere, and can be fixed with a bunch of ways such as
- documenting it in the values file [logging section](https://github.com/haproxytech/helm-charts/blob/31776dfe9814e34fd30f7b5d0440cad72de24cdd/kubernetes-ingress/values.yaml#L343)
- documenting it in the [Global Custom Resource](https://www.haproxy.com/documentation/kubernetes-ingress/community/configuration-reference/global-crd/) docs
- not having the Custom resource overwrite the other settings
- removing from either the Global CRD or the values file
