### ISSUE TITLE
Regular expressions in "path" do not appear to work

### ISSUE THREAD

**Issue by erulabs** [haproxytech/kubernetes-ingress#636]
I cannot find documentation on how to use regular expressions in paths in Ingress documents using haproxy-ingress-controller.

I'm using the `haproxytech/kubernetes-ingress` helm chart version 1.38.4 and haproxy-ingress version 1.11.1.

Given the following ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: sentry
    meta.helm.sh/release-namespace: sentry
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: sentry
  namespace: sentry
spec:
  ingressClassName: haproxy
  rules:
  - host: sentry.prod.internal.DOMAIN...
    http:
      paths:
      - backend:
          service:
            name: sentry-relay
            port:
              number: 3000
        path: /api/[1-9][0-9]*/(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: sentry-web
            port:
              number: 9000
        path: /
        pathType: ImplementationSpecific
```
All requests match only the `/` backend, as `/api/[1-9][0-9]*/(.*)` is written literally to `/etc/haproxy/maps/path-exact.map` and does not appear to be checked as a regular expression.

Note that while nginx ingress has a "nginx.ingress.kubernetes.io/use-regex" annotation, I cannot find anything of the sort for haproxy-ingress.

So, my question is:
1. Is it possible to use regular expressions in haproxy-ingress-controller today? If so, how?
2. Can we add documentation somewhere to this repo to give an example of regular expression paths? I would be happy to contribute documentation but I need some hints!

Thank you!

**Comment by ivanmatmati** [comment]
Hi @erulabs , at the moment this is not possible. We don't support directly the regex in paths. But you can try to implement it with the [route-acl](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/annotations.md#route-acl) annotation at the service level.

**Comment by unixbird** [comment]
> Hi [@erulabs](https://github.com/erulabs) , at the moment this is not possible. We don't support directly the regex in paths. But you can try to implement it with the [route-acl](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/annotations.md#route-acl) annotation at the service level.

Is this still the case? Just switched off of ingress-nginx and if so that'd be a big bummer. It mentions in the docs that regex is enabled by default when looking for equivalent annotations here: https://www.haproxy.com/ingress-nginx-migration-assistant

**Comment by hetii** [comment]
@erulabs Why this is closed?
haproxy claims  to be a replacement for ingress nginx and support for this use case imho is a basic stuff.
Please kindly let us know what's the current status of it or at least workaround examples.

**Comment by rlnorthcutt** [comment]
I see the challenge. When you lookup `use-regex` in the tool, it says _"No equivalent. HAProxy path-rewrite uses regex by default."_ This might make you think that it is "default" for any path, but it really means that it is the default for the `path-rewrite` annotation. I've asked to update the tool with a [link to the docs.](https://www.haproxy.com/documentation/kubernetes-ingress/community/configuration-reference/ingress/#path-rewrite)

The core issue is that HAProxy's Ingress controller maps the standard `path` field to high-performance **Map files**, which are optimized for literal lookups, not regex evaluation. If you put a regex in the `path` field, HAProxy treats it as a literal string (which is why you see `/api/[1-9]...` in your `path-exact.map`). Note that these are case sensitive as well.

In NGINX, you often use `use-regex` in tandem with `rewrite-target`. In HAProxy, the single `path-rewrite` annotation handles both the matching logic and the transformation logic.

## How to solve this today:

Since the `use-regex` annotation isn't supported, you have two main workarounds:

### 1. Use `path-rewrite`

Even if you don't need to change the URL, the `haproxy.org/path-rewrite` annotation triggers HAProxy’s regex engine. You can use it to match your complex path and 'rewrite' it to itself.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: default
  annotations:
    haproxy.org/path-rewrite: "/"                        # replace all paths with /
    haproxy.org/path-rewrite: (.*) /foo\1                # add the prefix /foo... "/bar?q=1" into "/foo/bar?q=1"
    haproxy.org/path-rewrite: ([^?]*)(\?(.*))? \1/foo\2  # add the suffix /foo ... "/bar?q=1" into "/bar/foo?q=1"
    haproxy.org/path-rewrite: /foo/(.*) /\1              # strip /foo ... "/foo/bar?q=1" into "/bar?q=1"
    
    # strip /foo ... "/foo/bar?q=1" into "/bar?q=1" and replace "/bar/*" with "/baz/*"
    # with multiline (using `|`) annotation
    haproxy.org/path-rewrite: |
      /foo/(.*) /\1
      /bar/(.*) /baz/\1

```

### 2. Use `route-acl` 

As suggested above, you can bypass the standard path mapping entirely by using an ACL at the service level. This is more verbose but the most powerful.

```yaml
# In your Service metadata
annotations:
  haproxy.org/route-acl: "path_reg ^/api/[1-9][0-9]*/.*"

```
