### ISSUE TITLE
Docs: when adjusting --sync-period, must also adjust initialDelaySeconds

### ISSUE THREAD

**Issue by axmorris** [haproxytech/kubernetes-ingress#651]
(HAProxy Technologies Documentation Team) Requesting the following changes to kubernetes-ingress/documentation/doc.yaml regarding `--sync-period`.

Info: 
If you increase the `--sync-period` startup argument then you also need to increase the `startupProbe`'s `initialDelaySeconds` value. The value for `initialDelaySeconds` needs to be larger than the desired sync-period. Without the change to `startupProbe`, the IC pod will be stuck in a `CrashLoop` due to the startup probe failing. 

This requested change to the documentation provides a work around for a small percentage of users that require a larger `sync-period`.

The change to `doc.yaml`:

```
  - argument: --sync-period
    description: The interval at which the controller syncs its configuration with updated Kubernetes objects. In the case where the ingress controller is reloading too frequently, a higher value may be required. Note that you must also adjust the `startupProbe`'s `initialDelaySeconds` value. Its value must be higher than the `--sync-period` value.
    values:
      - An integer with unit of time (1s = 1 second, 1m = 1 minute, 1h = 1 hour); Defaults to 5s
    default: 5s
    version_min: "1.4"
    example: --sync-period=60s
    helm: |-
      helm install haproxy haproxytech/kubernetes-ingress \
        --set-string "controller.extraArgs={--sync-period=60s}" \
        --set controller.startupProbe.initialDelaySeconds=80
```
