### ISSUE TITLE
how enable only high secure ssl ciphers in haproxy ingress?

### ISSUE THREAD

**Issue by agonzalezm** [haproxytech/kubernetes-ingress#659]
default haproxy ingress install has many yellow insecure ciphers enabled, how can i enable only secure ciphers (green ones)

![image](https://github.com/haproxytech/kubernetes-ingress/assets/2251991/7cae796f-4376-4ed9-9133-480a8eb6fe59)

**Comment by agonzalezm** [comment]
anyone can explain details how to remove these ciphers with haproxy ingress helm charts installed?

**Comment by fabianonunes** [comment]
You can use the `global-config-snippet` option in ConfigMap to set the ciphers:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-kubernetes-ingress
  namespace: default
data:
  global-config-snippet: |
    ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    ssl-default-bind-options prefer-client-ciphers no-sslv3 no-tlsv10 no-tlsv11 no-tlsv12 no-tls-tickets
```
