### ISSUE TITLE
Some clarification needed for handling canary deployments

### ISSUE THREAD

**Issue by pawellrus** [haproxytech/kubernetes-ingress#664]
Hello.
I tried to implement the solution described here (https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/canary-deployment.md) and found some problems.

My scenario is similar with the described one: two services: one of them is main while second is canary.
Both of them has similar path to running application. When I fully apply configuration, I see that only one rule is generated inside frontend. No matter what I try: one ingress, separate ingress per-service, standalone-backend annotation,  I cannot achieve needed configuration inside haproxy.

Basic configuration looks like in example from documentation:

```
apiVersion: v1
kind: Service
metadata:  
  name: gateway-service-main
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app.kubernetes.io/name: core-gateway
    environment: backend
---
apiVersion: v1
kind: Service
metadata:  
  name: gateway-service-canary
  annotations:
    haproxy.org/route-acl: hdr(device-id) -f /etc/haproxy/files/canary-deviceid.lst -i
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app.kubernetes.io/name: core-gateway
    canary: canary
    environment: backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-prod-like-gateway-any-internal-ingress
spec:
  ingressClassName: ingress-private
  tls:
    - hosts:
        [server.com]
      secretName: server.com
  rules:
    - host: "server.com"
      http:
        paths:
          - path: /prod-like
            pathType: ImplementationSpecific
            backend:
              service:
                name: gateway-service-main
                port:
                  number: 8080
                
          - pathType: ImplementationSpecific
            backend:
              service:
                name: gateway-service-canary
                port:
                  number: 8080
```

Routing section looks like that:

```
  use_backend prod-like_gateway-service-canary_8080 if { var(txn.host) -m str server.com }  { path -m beg /api }  { hdr(device-id) -f /etc/haproxy/files/canary-deviceid.lst -i }
  use_backend %[var(txn.path_match),field(1,.)]
```
So as far as I understad, it will route to only canary application.

I think that documentation needs to be clarified in this part: 

> We can have ingress rules for staging and production in the same ingress resource but they should not share the same path otherwise the latter will overwrite the former. To avoid any confusion we can have rules in different ingress resources.

Does it mean that case with same paths is fully impossible? Or it can be achieved with multiple ingress objects? If yes, could you please add working example?

Thank you.
