### ISSUE TITLE
Possibility to add custom stick tables

### ISSUE THREAD

**Issue by schferbe** [haproxytech/kubernetes-ingress#668]
We want to migrate from HAProxy installed on a VM to a HAProxy K8s Ingress. In our `haproxy.cfg` we have defined multiple dummy backends for additional stick tables. We use this to have a multi-layered rate limiting. Something akin to limiting requests per 1h and per 24h separately. 

We can comfortably port most of the configuration using either the `backend-config-snippet` annotation in the Ingress or `frontend-config-snippet` ConfigMap option. 

What is missing is the option to add custom backends. I would think about something like this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-kubernetes-ingress
  namespace: default
data: config-snippet: |
    backend st_ip_req_rate_24
        stick-table  type ip size 100k expire 24h  store http_req_rate(24h)

    backend st_ip_req_rate_1h
        stick-table  type ip size 100k expire 1h store http_req_rate(1h)

```

If I missed some option to add more stick tables, I'd also be happy for pointers.
