### ISSUE TITLE
scale-server-slots on Ingress resource is ignored

### ISSUE THREAD

**Issue by mike-code** [haproxytech/kubernetes-ingress#670]
**appVersion: 3.0.1**

Using the following `Ingress`

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-thanos
  namespace: monitoring
  annotations:
    haproxy.org/scale-server-slots: "4"
spec:
  ingressClassName: haproxy-thanos
  rules:
  - host: "..."
    http:
      ...
```

the backend still scales to `42`.
