### ISSUE TITLE
Switching back to an old Deployment is not registered by controller

### ISSUE THREAD

**Issue by NickMRamirez** [haproxytech/kubernetes-ingress#69]
## Problem

The controller does not add servers if those servers were added and removed previously when the pod selector was changed (such as to change the 'version' from 1.0 to 1.1, then back 1.0) on the service's Service.

## Environment

* Kubernetes v1.14.2
* Minikube v1.1.0
* haproxytech/kubernetes-ingress (469f92704ba5395ffbd38c10ac32538c23823a14e2ca474abca281ff8b74bae7)

## How to reproduce

1. Add 2 Deployments that are identical except that they have different labels:

*Blue Deployment*:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: app
  name: app-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      run: app
      scope: blue
  template:
    metadata:
      labels:
        run: app
        scope: blue
    spec:
      containers:
      - name: app
        image: quay.io/nickmramirez/webapp
        ports:
        - containerPort: 80
```

*Green Deployment*:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: app
  name: app-green
spec:
  replicas: 1
  selector:
    matchLabels:
      run: app
      scope: green
  template:
    metadata:
      labels:
        run: app
        scope: green
    spec:
      containers:
      - name: app
        image: quay.io/nickmramirez/webapp
        ports:
        - containerPort: 80
```

2. Add a service that points to *Blue Deployment*:

```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: app
  name: app
spec:
  selector:
    run: app
    scope: blue
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    targetPort: 80
```

3. Add an Ingress:

```
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: app
          servicePort: 80
```

4. At this point, the *blue* servers are added to the HAProxy Stats page. Next, change the `Service` so that its *scope* selector is *green*. HAProxy will remove the blue server and add the green server. So far, so good.

5. Change the *scope* selector on the `Service` back to *blue*. This time, the *green* servers are removed, but the *blue* servers are not added.
