### ISSUE TITLE
Warning "Secret '[...]' not registered with controller !" for secrets created by rook ceph ObjectBucketClaim

### ISSUE THREAD

**Issue by phihos** [haproxytech/kubernetes-ingress#696]
After upgrading the IC from 1.11 to 3.0 we suddenly got this warning two times:
```
WARNING store/events.go:250  Secret '[...]' not registered with controller !
```

In both cases it was a secret generated for a [ObjectBucketClaim](https://rook.io/docs/rook/v1.10/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim/) resource. It is apparent that this is not intended.

Theory: Both secrets have an owner reference like this:

```
  ownerReferences:
  - apiVersion: objectbucket.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ObjectBucketClaim
```

Could it be that the IC watches an overly broad selector which checks for `ownerReferences[*].controller==true` or similar?
