### ISSUE TITLE
Warning "Ingress HTTP rules for [...] does not exists" for ingresses that belong to different IC

### ISSUE THREAD

**Issue by phihos** [haproxytech/kubernetes-ingress#697]
When the K8S cluster has an ingress like this:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: somename
  namespace: somenamespace
spec:
  ingressClassName: nginx
  rules:
  - host: some.tld
```

HAProxy IC will complain about it even though the ingress class is wrong:

```
WARNING store/convert.go:99  Ingress HTTP rules for [some.tld] does not exists
```

Similar to #696 I assume an overly broad selector. If this turns out to be a general issue: It is important that the IC only watches resources where it is necessary. Not just to avoid false warning messages. In clusters with a lot of watched (ingress) resources this puts unnecessary strain on the kube-api server and can contribute to overloading it!
