### ISSUE TITLE
TCPRoute not taking in account weight

### ISSUE THREAD

**Issue by jfpucheu** [haproxytech/kubernetes-ingress#698]
Hello ,

I have an issue using TCPRoute in gateway with weight parameter. It seems weight parameter is never taken into account.

Version:
HAProxy version 3.0.2-a45a8e6 2024/06/14 - https://haproxy.org/
chart: "kubernetes-ingress"
version: "1.41.0"

My TCPRoute:

```
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: example-route
  namespace: default
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      namespace: ingress-haproxy
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: example-service-1
          weight: 255
          port: 80
        - group: ''
          kind: Service
          name: example-service-2
          weight: 1
          port: 80
```

And the config generated:

```
backend default_example-route
  mode tcp
  default-server check
  server SRV_1 172.20.225.118:8080 enabled
  server SRV_2 172.20.225.115:8080 enabled
```

Am I doing something wrong ?

thanks 
Jeff
