### ISSUE TITLE
haproxy-ingress does not respect ssl annotations

### ISSUE THREAD

**Issue by nkalev** [haproxytech/kubernetes-ingress#98]
Hi team,

In the new releases 1.2.0 + when i configure ssl annotations :
```yaml
ssl-certificate: "default/haproxy-tls-secret",
ssl-numproc: "3",
ssl-passthrough: "true",
ssl-redirect: "ON",
ssl-redirect-code: "302"
```
Enabling or disabling passthrough or ssl-redirect does not reflect the configuration in running pods. I'm using haproxy helm chart v0.0.4 https://hub.helm.sh/charts/mirusresearch/haproxytech-haproxy-ingress.
Is this intended behaviour ?

Regards,
Nikolay
